// places-data.js - Catálogo de Recomendaciones Curadas - Puerto Varas por Mamá Santi (@datitosdelajose)
// Coordenadas georreferenciadas exactas en torno a Puerto Varas, Ensenada, Frutillar y el Lago Llanquihue.
// Incluye enlaces directos a Airbnb, WhatsApp verificado y recomendaciones en video.

const PLACES_DATA = [
  {
    id: "domos-anulen",
    name: "Domos & Cabañas Anulén",
    category: "hoteles",
    categoryBadge: "🏡 Cabaña & Airbnb · Tinaja & Vista Volcán",
    rating: 5.0,
    reviewsCount: 380,
    image: "thumbs/thumb_DI2AjSZPe8b.jpg",
    personalTip: "Cada domo y cabaña tiene su propia tinaja caliente de madera y parrilla en la terraza con una postal panorámica al Volcán Osorno. Ideal para desconectar en pareja o familia.",
    shortDesc: "Domos geodésicos y cabañas rústicas de madera con tinaja privada y vistas abiertas al volcán.",
    address: "Ruta 225 Km 25.9, Sector Los Riscos, Puerto Varas",
    coordinates: { lat: -41.2550, lng: -72.7830 },
    duration: "Estadía / Noche",
    priceRange: "$$$",
    whatsapp: "+56997164401",
    instagram: "@domosanulen",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Domos%20Anulen%20Los%20Riscos",
    curatorNote: "Recomendado 100% en video por la Jose",
    featured: true,
    tags: ["cabanas", "airbnb", "domos", "tinajas", "volcanosorno", "losriscos"]
  },
  {
    id: "cantos-del-chucao",
    name: "Cabañas Cantos del Chucao",
    category: "hoteles",
    categoryBadge: "🏡 Cabaña & Airbnb · Calificación 10/10",
    rating: 5.0,
    reviewsCount: 290,
    image: "thumbs/thumb_C-wDBXtu6Us.jpg",
    personalTip: "¡Mi nota es 10/10! A solo 20 minutos de Puerto Varas en medio del bosque nativo. Cabaña íntima para 2 personas con tinaja de ciprés, parrilla y combustión lenta.",
    shortDesc: "Cabañas escondidas en el bosque templado con tinaja de ciprés y estufa a leña.",
    address: "Sector Colonia Tres Puentes, a 19 km de Puerto Varas",
    coordinates: { lat: -41.3850, lng: -72.8710 },
    duration: "Estadía / Noche",
    priceRange: "$$",
    whatsapp: "+56983244111",
    instagram: "@cantosdelchucao",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Cantos%20del%20Chucao%20Tres%20Puentes",
    curatorNote: "Elegida 10/10 por Mamá Santi",
    featured: true,
    tags: ["cabanas", "airbnb", "bosque", "tinaja", "romantico", "chucao"]
  },
  {
    id: "cabanas-rucamalen",
    name: "Cabañas Rucamalén & Piscina Climatizada",
    category: "hoteles",
    categoryBadge: "🏊‍♀️ Cabaña & Spa · Piscina Climatizada",
    rating: 4.9,
    reviewsCount: 520,
    image: "thumbs/thumb_DIg8vHpA9A0.jpg",
    personalTip: "Puedes ir por el día sin ser huésped: Piscina climatizada 4 hrs ($15.000 adultos, $10.000 niños), tinajas calientes, sauna y bajada al lago.",
    shortDesc: "Complejo a orillas del lago Llanquihue con piscina temperada techada, tinajas y kayaks.",
    address: "Camino a Ensenada Km 36, Puerto Varas",
    coordinates: { lat: -41.2310, lng: -72.6350 },
    duration: "4 horas / Estadía",
    priceRange: "$$$",
    whatsapp: "+56956482005",
    instagram: "@cabanas__rucamalen",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Cabanas%20Rucamalen%20Ensenada",
    curatorNote: "Piscina climatizada abierta todo el año",
    featured: true,
    tags: ["cabanas", "airbnb", "piscina", "tinajas", "sauna", "lago"]
  },
  {
    id: "cabanas-bahia-celeste",
    name: "Cabañas Bahía Celeste",
    category: "hoteles",
    categoryBadge: "🏡 Cabaña & Airbnb · Orilla Directa de Lago",
    rating: 4.9,
    reviewsCount: 310,
    image: "thumbs/thumb_DHrIE4RPTD0.jpg",
    personalTip: "A solo 25 minutos de Puerto Varas. Cabañas para 2, 4, 5 y 6 personas situadas literalmente en la orilla de la playa con muelle propio y vista a los dos volcanes.",
    shortDesc: "Cabañas familiares sobre la ribera del lago Llanquihue con bajada privada a la arena.",
    address: "Ruta 225 Km 21, Camino a Ensenada, Puerto Varas",
    coordinates: { lat: -41.2610, lng: -72.8620 },
    duration: "Estadía / Noche",
    priceRange: "$$$",
    whatsapp: "+56993287634",
    instagram: "@bahia_celeste",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Bahia%20Celeste%20Cabanas%20Puerto%20Varas",
    curatorNote: "Playa privada y muelle sobre el lago",
    featured: true,
    tags: ["cabanas", "airbnb", "playa", "lago", "familia", "volcan"]
  },
  {
    id: "casa-pumahue",
    name: "Casa Pumahue · Cabañas & Glamping",
    category: "hoteles",
    categoryBadge: "🏡 Cabaña & Airbnb · Desayuno Pumahue",
    rating: 4.9,
    reviewsCount: 410,
    image: "thumbs/thumb_DIF0YQjgzZ6.jpg",
    personalTip: "Disfruta de la tinaja caliente de madera con vista despejada a los volcanes y pide el exquisito desayuno Pumahue con ingredientes de huerta.",
    shortDesc: "Cabañas y domos rústicos cercanos al Parque Nacional Vicente Pérez Rosales.",
    address: "Camino a Ensenada s/n, sector Ensenada, Puerto Varas",
    coordinates: { lat: -41.2050, lng: -72.5400 },
    duration: "Estadía / Noche",
    priceRange: "$$$",
    whatsapp: "+56973984624",
    instagram: "@casa_pumahue",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Casa%20Pumahue%20Ensenada",
    curatorNote: "Cercano a Saltos del Petrohué",
    featured: false,
    tags: ["cabanas", "airbnb", "glamping", "domos", "tinajas", "volcanes"]
  },
  {
    id: "refugio-rio-blanco",
    name: "Refugio Río Blanco · Cascada & Bosque",
    category: "hoteles",
    categoryBadge: "🏡 Cabaña & Airbnb · Tinaja en el Bosque",
    rating: 5.0,
    reviewsCount: 195,
    image: "thumbs/thumb_DMgjOk3PULT.jpg",
    personalTip: "Un lugar lleno de magia y silencio a menos de 1 hora del centro. Cabaña equipada para 5 personas con tinaja de agua caliente junto al murmullo de la cascada.",
    shortDesc: "Cabaña de montaña en el bosque nativo junto a la cascada Río Blanco.",
    address: "Camino a Ensenada, Sector Río Blanco, Puerto Varas",
    coordinates: { lat: -41.2820, lng: -72.7150 },
    duration: "Estadía / Noche",
    priceRange: "$$$",
    whatsapp: "+56997164401",
    instagram: "@refugio_rio.blanco",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Refugio%20Rio%20Blanco%20Cabana",
    curatorNote: "Pura desconexión y cascadas secretas",
    featured: true,
    tags: ["cabanas", "airbnb", "bosque", "cascada", "tinaja", "rioblanco"]
  },
  {
    id: "camping-suyai",
    name: "Camping & Cabañas Suyai Ensenada",
    category: "aventura",
    categoryBadge: "⛺️ Camping & Cabaña · Acceso al Lago",
    rating: 4.8,
    reviewsCount: 260,
    image: "thumbs/thumb_DVPWP04j4aq.jpg",
    personalTip: "Te dejo 3 opciones: Camping, sitios para asado/picnic y mini cabaña acogedora. Todo con bajada directa al lago Llanquihue. Por orden de llegada.",
    shortDesc: "Sitio de camping y mini cabaña frente a Copec Ensenada con acceso a la playa.",
    address: "Ruta 225 Km 42, frente a Copec, Ensenada, Puerto Varas",
    coordinates: { lat: -41.2090, lng: -72.5350 },
    duration: "Medio día / Estadía",
    priceRange: "$",
    whatsapp: "+56968507827",
    instagram: "@campingsuyaiensenada",
    airbnbUrl: "https://www.airbnb.cl/s/Ensenada--Los-Lagos--Chile/homes?query=Ensenada%20Puerto%20Varas%20Cabanas%20Lago",
    curatorNote: "Por orden de llegada, bajada al lago",
    featured: false,
    tags: ["cabanas", "airbnb", "camping", "asado", "ensenada", "lago"]
  },
  {
    id: "origen-patagonia-verde",
    name: "Origen Patagonia Verde · Yurta & Bosque",
    category: "aventura",
    categoryBadge: "🌿 Glamping & Airbnb · Yurta & Baños de Bosque",
    rating: 5.0,
    reviewsCount: 140,
    image: "thumbs/thumb_C2D-y1_OH3Z.jpg",
    personalTip: "Duerme en una yurta mongola en el bosque con tinaja privada. Además puedes agendar senderismo contemplativo guiado, Shinrin Yoku y yoga.",
    shortDesc: "Experiencia de inmersión en bosque templado con Yurta de lujo y baños de bosque.",
    address: "Sector Totoral, a 15 min de Puerto Varas",
    coordinates: { lat: -41.2890, lng: -73.0450 },
    duration: "Estadía / Experiencia",
    priceRange: "$$$",
    whatsapp: "+56942492462",
    instagram: "@origenpatagoniaverde",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Yurta%20Origen%20Patagonia%20Verde%20Totoral",
    curatorNote: "Shinrin Yoku & Yurta en Totoral",
    featured: true,
    tags: ["cabanas", "airbnb", "glamping", "yurta", "bosque", "yoga", "tinaja"]
  },
  {
    id: "camping-don-chucao",
    name: "Camping Don Chucao · Carpas Colgantes",
    category: "aventura",
    categoryBadge: "⛺️ Glamping Único · Dormir en el Aire",
    rating: 4.9,
    reviewsCount: 180,
    image: "thumbs/thumb_C3oOZL5OXWS.jpg",
    personalTip: "Ultra entretenida experiencia de dormir en carpas suspendidas en los árboles en medio del bosque. En la mañana, desayuno campestre casero con su dueña Mireya.",
    shortDesc: "Carpas colgantes en los árboles en Caleta Rollizo con desayuno artesanal sureño.",
    address: "A 86 km de Puerto Varas y a 700 m de Caleta Rollizo",
    coordinates: { lat: -41.5120, lng: -72.3780 },
    duration: "Estadía / Noche",
    priceRange: "$$",
    whatsapp: "+56979292090",
    instagram: "@campingdonchucao",
    airbnbUrl: "https://www.airbnb.cl/s/Caleta-Rollizo--Chile/homes?query=Camping%20Don%20Chucao%20Rollizo",
    curatorNote: "Experiencia única en Caleta Rollizo",
    featured: false,
    tags: ["cabanas", "airbnb", "glamping", "carpascolgantes", "bosque", "rollizo"]
  },
  {
    id: "hotel-germania-buffet",
    name: "Desayuno Buffet Hotel Germania",
    category: "lluvia",
    categoryBadge: "☕ Desayuno Buffet · $12.000 Todo Público",
    rating: 4.8,
    reviewsCount: 620,
    image: "thumbs/thumb_C8viWkou1y6.jpg",
    personalTip: "Todos los días de 7:00 a 11:00 hrs. Ricos productos locales, recetas alemanas generacionales y küchens caseros. El espacio y wifi son ideales si tienes que trabajar.",
    shortDesc: "Buffet tradicional con pastelería alemana de época en el centro de Puerto Varas.",
    address: "San Ignacio 1286, Puerto Varas",
    coordinates: { lat: -41.3215, lng: -72.9840 },
    duration: "1.5 horas",
    priceRange: "$$",
    whatsapp: "+56652232444",
    instagram: "@hotelgermania_puertovaras",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes",
    curatorNote: "Buffet abierto a público $12.000",
    featured: true,
    tags: ["lluvia", "buffet", "kuchen", "cafe", "germania"]
  },
  {
    id: "cafe-mawen",
    name: "Café Mawen & Küchens",
    category: "lluvia",
    categoryBadge: "🌧️ ¿Llueve hoy? · Café con Chimenea",
    rating: 4.9,
    reviewsCount: 840,
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
    personalTip: "Pide el küchen tibio de murta con frambuesa y busca la mesa redonda junto a la chimenea de leña. La vista al lago con lluvia es pura poesía.",
    shortDesc: "Cafetería íntima con repostería alemana casera y ventanales panorámicos al lago.",
    address: "Av. Vicente Pérez Rosales 1290, Puerto Varas",
    coordinates: { lat: -41.3175, lng: -72.9830 },
    duration: "1 hora",
    priceRange: "$$",
    whatsapp: "+56987654321",
    instagram: "@cafemawen.pv",
    airbnbUrl: null,
    curatorNote: "Recomendado por Mamá Santi",
    featured: true,
    tags: ["lluvia", "cafe", "pasteleria", "chimenea"]
  },
  {
    id: "mesa-tropera",
    name: "Mesa Tropera (Sobre el Lago)",
    category: "tragos",
    categoryBadge: "🍷 Cena & Tragos · Vistas al Lago",
    rating: 4.8,
    reviewsCount: 2310,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    personalTip: "Llega a las 19:30 para tomar una cerveza artesanal Tropera mientras el sol tiñe el Volcán Calbuco de rosa. Pide la pizza 'Volcánica' de masa madre.",
    shortDesc: "Pizzería y cervecería artesanal montada sobre palafitos dentro de las aguas del lago Llanquihue.",
    address: "Costanera San Pedro 550, Puerto Varas",
    coordinates: { lat: -41.3168, lng: -72.9772 },
    duration: "2 horas",
    priceRange: "$$$",
    whatsapp: "+56976543210",
    instagram: "@mesatropera",
    airbnbUrl: null,
    curatorNote: "El mejor atardecer de la ciudad",
    featured: true,
    tags: ["tragos", "despejado", "cerveza", "pizza", "atardecer"]
  },
  {
    id: "cerro-philippi",
    name: "Mirador Cerro Philippi",
    category: "despejado",
    categoryBadge: "☀️ Día Despejado · Miradores",
    rating: 4.8,
    reviewsCount: 1120,
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    personalTip: "Sube por el sendero arbolado entre canelos y coihues hasta la gran cruz. Es la postal icónica perfecta: Puerto Varas, la iglesia y el volcán en un solo encuadre.",
    shortDesc: "Parque urbano con senderos sombreados y vista panorámica en 360° de la cuenca del lago.",
    address: "Acceso por calle Phillippi s/n, Puerto Varas",
    coordinates: { lat: -41.3160, lng: -72.9875 },
    duration: "1.5 horas",
    priceRange: "Gratis",
    whatsapp: "+56999887766",
    instagram: "@puertovaras_chile",
    airbnbUrl: null,
    curatorNote: "Spot fotográfico imprescindible",
    featured: true,
    tags: ["despejado", "naturaleza", "mirador", "gratis"]
  },
  {
    id: "hotel-awa",
    name: "Hotel AWA Boutique & Spa",
    category: "hoteles",
    categoryBadge: "🏨 Hoteles con Encanto · Diseño",
    rating: 4.9,
    reviewsCount: 560,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    personalTip: "Incluso si no te hospedas, reserva una tarde en su spa de aguas termales templadas o un té de media tarde en su salón vidriado frente al volcán.",
    shortDesc: "Arquitectura vanguardista que rinde tributo a los materiales nobles del sur con vista despejada al Osorno.",
    address: "Ruta 225 Km 27, Ensenada - Puerto Varas",
    coordinates: { lat: -41.2589, lng: -72.8421 },
    duration: "Medio día / Estadía",
    priceRange: "$$$$",
    whatsapp: "+56911223344",
    instagram: "@hotelawa",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Hotel%20AWA",
    curatorNote: "Lujo patagónico en armonía",
    featured: false,
    tags: ["hoteles", "airbnb", "relax", "spa", "vistas"]
  },
  {
    id: "saltos-del-petrohue",
    name: "Saltos del Petrohué & Laguna Verde",
    category: "aventura",
    categoryBadge: "🌲 Aventura & Naturaleza · Parque Vicente Pérez Rosales",
    rating: 4.9,
    reviewsCount: 4890,
    image: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1200&q=80",
    personalTip: "Haz el sendero 'Los Enamorados'. El contraste de la roca basáltica volcánica con el agua color turquesa es surreal. Lleva cortavientos impermeable.",
    shortDesc: "Espectaculares cascadas de agua esmeralda esculpidas por la lava sobre el río Petrohué.",
    address: "Parque Nacional Vicente Pérez Rosales, Ruta 225",
    coordinates: { lat: -41.1762, lng: -72.4502 },
    duration: "3 horas",
    priceRange: "$ (Entrada Conaf)",
    whatsapp: "+56933445566",
    instagram: "@parquesnacionales.cl",
    airbnbUrl: null,
    curatorNote: "Maravilla natural del mundo",
    featured: true,
    tags: ["aventura", "naturaleza", "despejado", "cataratas"]
  },
  {
    id: "hotel-cabana-del-lago",
    name: "Hotel Cabaña del Lago & Tinajas",
    category: "hoteles",
    categoryBadge: "🏨 Hoteles & Spa · Desayuno Buffet & Tinajas",
    rating: 4.8,
    reviewsCount: 1400,
    image: "thumbs/thumb_DHT3z_KvxTF.jpg",
    personalTip: "Desayuno buffet con pastelería propia abierto a todo público (7:00 a 10:30) y pack de almuerzo con acceso a la piscina climatizada más grande de la región ($36.900 adultos).",
    shortDesc: "Hotel de arquitectura tradicional germano-chilota con vista a los tres volcanes y gran piscina templada.",
    address: "Klenner 195, Puerto Varas",
    coordinates: { lat: -41.3235, lng: -72.9805 },
    duration: "Estadía / Pase diario",
    priceRange: "$$$",
    whatsapp: "+56999001122",
    instagram: "@hotel_cdl",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Hotel%20Cabana%20del%20Lago",
    curatorNote: "Piscina climatizada & buffet abierto",
    featured: true,
    tags: ["hoteles", "airbnb", "piscina", "tinajas", "spa", "buffet"]
  }
];

function getPlaceById(id) {
  return PLACES_DATA.find(place => place.id === id);
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PLACES_DATA, getPlaceById };
}
