// Catálogo de Promociones y Beneficios Vigentes - Datitos de la Jose
// Generado automáticamente desde: Top 100 Locales Filtrados y Recientes - Datitos de la Jose (Fase 1).xlsx
// Total promociones: 12

const PROMOS_DATA = [
  {
    "id": "PROMO-01",
    "name": "Wyndham Pettra Puerto Varas",
    "brand": "Wyndham Pettra Puerto Varas",
    "category": "descuentos",
    "categoryBadge": "🍹 2x1 / Promoción",
    "benefitType": "Promoción Buffet",
    "discount": "2x1 en Buffet de Sushi los jueves",
    "status": "Activo",
    "schedule": "Jueves de 19:30 a 22:30",
    "howToRedeem": "Mencionar a Datitos de la Jose al reservar mesa.",
    "shortDesc": "Promoción Buffet · Jueves de 19:30 a 22:30",
    "personalTip": "2x1 en Buffet de Sushi los jueves. Canje: Mencionar a Datitos de la Jose al reservar mesa.",
    "fullCaption": "🍣 Atención sushi lovers!! Buffet de sushi en @pettra.restaurante de Hotel @wyndhampettra \n• Todos los jueves de 19:30 a 21:30 hrs.\n• Valores: $25.500 adultos y $18.900 niños\n• Reservas: WhatsApp +56988805004\n📍Av. Imperial 561 Puerto Varas\n\n#sushilovers #puertovaraschile",
    "image": "thumbs/thumb_DWaFRsYgOF6.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://scontent-lhr11-1.cdninstagram.com/o1/v/t2/f2/m86/AQON5J1g37l4tiRAtqFqos3TGswE5pzpBKTMI3wS060bwq0FjtF-k_KUrhgD5bjsyilYua0FZW5yGezBpfjzAOu0C-V1FHpiLfQAAc8.mp4?_nc_cat=107&_nc_sid=5e9851&_nc_ht=scontent-lhr11-1.cdninstagram.com&_nc_ohc=uxpmdrM40mwQ7kNvwEq0eRs&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc5NTY4MjExMTQwOTc3MDYsImFzc2V0X2FnZV9kYXlzIjoxNzMsInZpX3VzZWNhc2VfaWQiOjEwODI3LCJkdXJhdGlvbl9zIjoyNSwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=ca2171b58e0cd78a&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9FODRCRjU4QkQwODU3RTQ0MTc2Qzc5QUNGQkJGRDg5NV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyL0M2NDUwMUEzMTY0NEYyRjlGMkE5RDZBQkU1NjkyRTlGX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbUwOj8xujlPxUCKAJDMywXQDkIcrAgxJwYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZZapAQA&_nc_gid=A1F6wAwl4FKsv-s1I-4EpQ&_nc_zt=28&_nc_ss=7a22e&oh=00_AQIrHuthzwTPV27BNb67cK4_AyjPfub7-n-GdYwLM_OIFA&oe=6AAE1E40",
    "shortCode": "DWaFRsYgOF6",
    "url": "https://www.instagram.com/p/DWaFRsYgOF6/",
    "instagramUrl": "https://www.instagram.com/p/DWaFRsYgOF6/",
    "rating": 5,
    "reviewsCount": 1916,
    "commentsCount": 54,
    "tags": [
      "wyndham pettra puerto varas",
      "descuentos",
      "promoción buffet",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-02",
    "name": "La Cantina 340",
    "brand": "La Cantina 340",
    "category": "descuentos",
    "categoryBadge": "🔥 Descuento Especial",
    "benefitType": "Descuento en Carta",
    "discount": "15% de descuento en Champipapas y pizzas",
    "status": "Activo",
    "schedule": "Lunes a Jueves",
    "howToRedeem": "Mostrar que sigues a @datitosdelajose al pedir la cuenta.",
    "shortDesc": "Descuento en Carta · Lunes a Jueves",
    "personalTip": "15% de descuento en Champipapas y pizzas. Canje: Mostrar que sigues a @datitosdelajose al pedir la cuenta.",
    "fullCaption": "🧀🍄 Es que de verdad es increible la tabla Champipapas de @lacantina340 \n😋 Champiñones, tocino, salsa de 4 quesos (roquefort, mozzarella, cheddar y queso de campo) Todo sobre 1 capa de papas fritas. Valor: $12.800\n🥂 Tienen Happy Hour de martes a jueves de 17:00 a 21:00 hrs.\n\n📍Santa Rosa 340. Pleno centro de Puerto Varas\n\n#salsa4quesos #salsacuatroquesos #salsadechampiñones #tablasdepicoteo #restaurant #bar #saboresdelsur #salidanocturna #happyhour #centrodepuertovaras #buendato #puertovaras #puertovaraschile #surdechile",
    "image": "thumbs/thumb_CruRRV4NK-Q.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://scontent-ssn1-1.cdninstagram.com/o1/v/t2/f2/m82/AQNw4P5fXT2iAeHCqr4G97FtHZ_8zZqqKhH33RnYXmPLvuwgXGYUisBbn2nFHa1nB-A967CUuAMyqkJbAj_-peIEBWcVreEKqIBabHs.mp4?_nc_cat=109&_nc_sid=5e9851&_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_ohc=2dtJe0IvOBYQ7kNvwGFFb1x&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTQyMzgzNDU1ODQ0NzgzMywiYXNzZXRfYWdlX2RheXMiOjEyMzQsInZpX3VzZWNhc2VfaWQiOjEwMDk5LCJkdXJhdGlvbl9zIjoyMSwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=994cdc106b2cc4fc&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC81QzQ5NDQ1NDFDMEFDNjYzODM3NTk0RDE5RTQxRTJCQl92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HSjctakJTVzVHcE9iTVlGQUdnaDBqZ0stWmtQYnFfRUFBQUYVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmsoOakYq-hwUVAigCQzMsF0A1mZmZmZmaGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHX-B2XmnQEA&_nc_gid=mA1KbYq68k59WXCrcUCWew&_nc_ss=7a22e&_nc_zt=28&oh=00_AQKwV-QgyWf1tqpFM4cwpRxt1H-lgC-HNvQwilMvzRKMPQ&oe=6AAE4446",
    "shortCode": "CruRRV4NK-Q",
    "url": "https://www.instagram.com/p/CruRRV4NK-Q/",
    "instagramUrl": "https://www.instagram.com/p/CruRRV4NK-Q/",
    "rating": 5,
    "reviewsCount": 284,
    "commentsCount": 22,
    "tags": [
      "la cantina 340",
      "descuentos",
      "descuento en carta",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-03",
    "name": "Domos y Cabañas Anulen",
    "brand": "Domos y Cabañas Anulen",
    "category": "sorteos",
    "categoryBadge": "🎁 Sorteo Activo",
    "benefitType": "Sorteo Estadía",
    "discount": "Sorteo de 1 noche para 2 con tinaja privada",
    "status": "Finalizado",
    "schedule": "Sorteado en historias",
    "howToRedeem": "Ver ganadora en historias destacadas de @datitosdelajose.",
    "shortDesc": "Sorteo Estadía · Sorteado en historias",
    "personalTip": "Sorteo de 1 noche para 2 con tinaja privada. Canje: Ver ganadora en historias destacadas de @datitosdelajose.",
    "fullCaption": "🌅 ¡Relajo mágico en @domosanulen y @cabanasanulen \n👨‍👩‍👦‍👦 ¡Lo pasamos realmente increíble! Cada domo y cabaña tiene su tinaja y parrilla en la terraza con una hermosa vista al volcán Osorno\n📍Km. 25.9 Sector Los Riscos, camino a Ensenada, Puerto Varas\n📲 +56997164401\n\n#domos #cabañas #relajomaximo #recomiendo #ensenadachile #puertovaras #puertovaraschile",
    "image": "thumbs/thumb_DI2AjSZPe8b.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://scontent-ord5-2.cdninstagram.com/o1/v/t2/f2/m367/AQM97eUnGtyAHSx9q1NC3PGH7WaQmITHCfet5jfl2DB6diKkebG50NLqh1ABMDDdFiyMKNW1hNO90aruuoX0oGyx-CgZLa3PMm132DQ.mp4?_nc_cat=103&_nc_sid=5e9851&_nc_ht=scontent-ord5-2.cdninstagram.com&_nc_ohc=Kt8vlidbSZ4Q7kNvwGxCLX5&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTE5MTg4NzkyOTMzODk4MSwiYXNzZXRfYWdlX2RheXMiOjUxMCwidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjIxLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=667744ef9d84d8e1&_nc_vs=HBksFQIYQGlnX2VwaGVtZXJhbC9BRjQ3OUNDRjUwODRCQ0NCM0U5RTIxNkVCRjQxOTk4RF92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYRmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC82NTQxMTAzODA4MzQ5MTJfMjUxNzQyODA5NzMxNzgxNjk5My5tcDQVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmyrGfioGBngQVAigCQzMsF0A1szMzMzMzGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHX-B2XmnQEA&_nc_gid=BKIkZXKKqf6KphrmuJICrA&_nc_ss=7a22e&_nc_zt=28&oh=00_AQJJ0Le1uIdESV9CQR22fCcZZPPf5qR0zxm5MbXBD3K7cA&oe=6AB2146C",
    "shortCode": "DI2AjSZPe8b",
    "url": "https://www.instagram.com/p/DI2AjSZPe8b/",
    "instagramUrl": "https://www.instagram.com/p/DI2AjSZPe8b/",
    "rating": 5,
    "reviewsCount": 95,
    "commentsCount": 8,
    "tags": [
      "domos y cabañas anulen",
      "sorteos",
      "sorteo estadía",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-04",
    "name": "Duck House Puerto Varas",
    "brand": "Duck House Puerto Varas",
    "category": "productos",
    "categoryBadge": "🎁 Regalo por Compra",
    "benefitType": "Regalo por Compra",
    "discount": "Pato de goma miniatura por compras > $15.000",
    "status": "Activo",
    "schedule": "Hasta agotar stock",
    "howToRedeem": "Decir en caja que vienes de parte de la Jose.",
    "shortDesc": "Regalo por Compra · Hasta agotar stock",
    "personalTip": "Pato de goma miniatura por compras > $15.000. Canje: Decir en caja que vienes de parte de la Jose.",
    "fullCaption": "🦆 ¡El mágico mundo de los patos de goma!\n¿Sabías que en Puerto Varas está la única tienda de patos de goma de Latinoamérica? @duckhouse.cl\n📍San Pedro 309, Puerto Varas, Chile.\n.\n.\n#patosdegoma #patitosdegoma #regalosunicos #coleccionistas #puertovaras #puertovaraschile #chile",
    "image": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://instagram.ftij1-2.fna.fbcdn.net/o1/v/t2/f2/m86/AQNwkE8eXuyyk1rUC34z5KCxyBHSk39BEVkBI4ReSiK9gF7UkXHHid7o_ReZVHYEZ8HPC_3zAYQQm0JUUVhUacEmAusX2Ln50PeQ9VA.mp4?_nc_cat=107&_nc_oc=AdrjAwGDZH46fpJkoUViroMtjVuujf1sbasGl7U4EBcTUq0laaUrz_T4fnACMT8KZViElW7TBt9gsiZB3zGDn9zG&_nc_sid=5e9851&_nc_ht=instagram.ftij1-2.fna.fbcdn.net&_nc_ohc=rKq6DQfXO20Q7kNvwGhq2sS&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6NDg2NTE3OTE5OTU1MzM5LCJhc3NldF9hZ2VfZGF5cyI6MTQ5MywidmlfdXNlY2FzZV9pZCI6MTAwOTksImR1cmF0aW9uX3MiOjE2LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=d0aba634302a2162&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8yMzRGQkRCRjkyMTFDQTZBRTc2QzM2MkQ4NkQyNDA5Nl92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HSE5OM2hFYTVuQWc1czRDQUNteVVaak5PeThPYnFfRUFBQUYVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmlubd_Iif3QEVAigCQzMsF0Aw3bItDlYEGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHX-B2XmnQEA&_nc_gid=pu_6W8vcM9Tw038UiLdwYw&_nc_ss=7a22e&_nc_zt=28&oh=00_AQIKjKTJpuJ0lwWmEWfJmVPFwcfuvnffGp8EgGubF8Tl9w&oe=6AAE2410",
    "shortCode": "ChTBeh9FSSE",
    "url": "https://www.instagram.com/p/ChTBeh9FSSE/",
    "instagramUrl": "https://www.instagram.com/p/ChTBeh9FSSE/",
    "rating": 5,
    "reviewsCount": 62,
    "commentsCount": 40,
    "tags": [
      "duck house puerto varas",
      "productos",
      "regalo por compra",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-05",
    "name": "Heisenburger Puerto Varas",
    "brand": "Heisenburger Puerto Varas",
    "category": "productos",
    "categoryBadge": "🎁 Regalo por Compra",
    "benefitType": "Regalo en Combo",
    "discount": "Porción de papas rústicas gratis con tu burger",
    "status": "Activo",
    "schedule": "Miércoles y Jueves",
    "howToRedeem": "Mostrar el Reel guardado al hacer el pedido en caja.",
    "shortDesc": "Regalo en Combo · Miércoles y Jueves",
    "personalTip": "Porción de papas rústicas gratis con tu burger. Canje: Mostrar el Reel guardado al hacer el pedido en caja.",
    "fullCaption": "🚓 ¡Me robaron mi hamburguesa @heisenburgerchile en Parque Estación Puerto Varas\n🤭🤭🤭\n\n#puertovaraschile",
    "image": "thumbs/thumb_DWNEEsfj2-2.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://scontent-gru1-1.cdninstagram.com/o1/v/t2/f2/m86/AQPypxDDb4Pv_XWfobpMxv1G1bktdFl9GO4pDf7qbzVs_3ZzoSefEjFcZ5uNWNIVqIez9SKm9Ua3b8ygWavToP_6Dxmtj04vUnnFbJ0.mp4?_nc_cat=101&_nc_sid=5e9851&_nc_ht=scontent-gru1-1.cdninstagram.com&_nc_ohc=GG4jDqS_uTwQ7kNvwHkrRxZ&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc5NTU4NDY4OTcwOTc3MDYsImFzc2V0X2FnZV9kYXlzIjoxNzgsInZpX3VzZWNhc2VfaWQiOjEwODI3LCJkdXJhdGlvbl9zIjo5LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=b8d1805e77928357&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8yNjRDM0QzQjZDQTM5NDg3MjE3NzlBQThCODhCRDBCOV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzdCNDNGMEMxREY0QkQzOUM3MkQ5NUMyNTg1RDIyQkI0X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbU74q_7K_lPxUCKAJDMywXQCMhysCDEm8YEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZZapAQA&_nc_gid=YOw3bh3zHiL_GGmDwH5MQQ&_nc_ss=7a22e&_nc_zt=28&oh=00_AQJxMZqcSuOj_ppaCFqdCkQJxmeCZ_4NYBUZOKgyOy_nqg&oe=6AAE1C76",
    "shortCode": "DWNEEsfj2-2",
    "url": "https://www.instagram.com/p/DWNEEsfj2-2/",
    "instagramUrl": "https://www.instagram.com/p/DWNEEsfj2-2/",
    "rating": 5,
    "reviewsCount": 169,
    "commentsCount": 18,
    "tags": [
      "heisenburger puerto varas",
      "productos",
      "regalo en combo",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-06",
    "name": "Nós Açaí Bar",
    "brand": "Nós Açaí Bar",
    "category": "productos",
    "categoryBadge": "🎁 Regalo por Compra",
    "benefitType": "Topping Extra Gratis",
    "discount": "Topping premium de avellana o fruta adicional gratis",
    "status": "Activo",
    "schedule": "Todos los días",
    "howToRedeem": "Mencionar el dato de la Jose al armar tu bowl.",
    "shortDesc": "Topping Extra Gratis · Todos los días",
    "personalTip": "Topping premium de avellana o fruta adicional gratis. Canje: Mencionar el dato de la Jose al armar tu bowl.",
    "fullCaption": "🍨 Probé los exquisitos @nos_acaibar y me encantaron!!! ¿Sabías que los topins son ilimitados?\n🤳 Y obvio que @datitosdelajose tenía que estar presente!!!!\n🥳 ¡Gran inauguración! Sábado 20 de diciembre desde las 16:00 y para las primeras 100 personas que lleguen, habrá bowl AÇAí gratis!!\n📍Santa Rosa 575 Pleno centro de Puerto Varas\n\n#açai #inauguracion #puertovaraschile",
    "image": "thumbs/thumb_DSaxRsyD2qu.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://scontent-ssn1-1.cdninstagram.com/o1/v/t2/f2/m86/AQMNtatKmbvg-Ldw9Hyish27Hh28Y11CjrUaiCw8xYnm0hH2QE8hsgqo9hAw5kTaPzYNDtgo-Fbgoao46F8rZmnbG4bmZE9qFi2KNRY.mp4?_nc_cat=111&_nc_sid=5e9851&_nc_ht=scontent-ssn1-1.cdninstagram.com&_nc_ohc=28S326opiBsQ7kNvwGA6PIB&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6NzM4ODEwODc1OTM1NTI0LCJhc3NldF9hZ2VfZGF5cyI6MjczLCJ2aV91c2VjYXNlX2lkIjoxMDgyNywiZHVyYXRpb25fcyI6MjMsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=4f8c3f528d37a902&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9BQzQxN0FBMzg2RUY3N0RCNTZCOTgyRjUzMThEMTBBM192aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HRUkxcUNQeXNJVzdkRmtGQUYxdk5sNlgybThUYnN0VEFRQUYVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmyOyH_bn8zwIVAigCQzMsF0A3VT987ZFoGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHX-B2WWqQEA&_nc_gid=fZyRDv8l6364SvfG5uQM0Q&_nc_ss=7a22e&_nc_zt=28&oh=00_AQIJZZq90ViWhAeoCXpuJ4jBV6ziRrLDhXEmBav09MWnlw&oe=6AAE2C08",
    "shortCode": "DSaxRsyD2qu",
    "url": "https://www.instagram.com/p/DSaxRsyD2qu/",
    "instagramUrl": "https://www.instagram.com/p/DSaxRsyD2qu/",
    "rating": 5,
    "reviewsCount": 216,
    "commentsCount": 10,
    "tags": [
      "nós açaí bar",
      "productos",
      "topping extra gratis",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-07",
    "name": "Sunset Dreams",
    "brand": "Sunset Dreams",
    "category": "descuentos",
    "categoryBadge": "🍹 2x1 / Promoción",
    "benefitType": "2x1 en Coctelería",
    "discount": "2x1 en cócteles de autor seleccionados de 18:00 a 20:00",
    "status": "Activo",
    "schedule": "Viernes y Sábados (Sunset Hour)",
    "howToRedeem": "Mencionar la promoción al garzón antes de pedir.",
    "shortDesc": "2x1 en Coctelería · Viernes y Sábados (Sunset Hour)",
    "personalTip": "2x1 en cócteles de autor seleccionados de 18:00 a 20:00. Canje: Mencionar la promoción al garzón antes de pedir.",
    "fullCaption": "🍹Ricos tragos de autor, tablas para compartir y una maravillosa vista al lago Llanquihue.\n🍸 @sunsetpuertovaras está en el segundo piso de Dream Puerto Varas \n🥂 Abierto de jueves a domingo \n\n#restobar #puertovaraschile",
    "image": "thumbs/thumb_DUFADW6AB6G.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://scontent-lax3-1.cdninstagram.com/o1/v/t2/f2/m86/AQMT7-qNlDCVT6_snfwogHrDpoIxqn7znEsSGrsO8yK1F9aaVdLJdi6cKJ19O1Clpp_xn7k-WHJuP7JUY6ymVFDrfTaPM6el14cQrco.mp4?_nc_cat=108&_nc_sid=5e9851&_nc_ht=scontent-lax3-1.cdninstagram.com&_nc_ohc=cMoanmhEckYQ7kNvwF7PlTL&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc5NDcwOTIwOTYwOTc3MDYsImFzc2V0X2FnZV9kYXlzIjoyMzEsInZpX3VzZWNhc2VfaWQiOjEwODI3LCJkdXJhdGlvbl9zIjo5LCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=c48c5e6a3462f8a6&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC8zNTQ1RjcyNTUxNzhFREFDRUI4OUNGMzg2MjRFMjM5MV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzE4NEM4NkZEOUVEMDREMzNGN0ZEQjhFMDdGOTMxNThEX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbU9pySoLLhPxUCKAJDMywXQCJmZmZmZmYYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZZapAQA&_nc_gid=8KsFAOs3ghOG5f4B81KA7w&_nc_ss=7a22e&_nc_zt=28&oh=00_AQKNkg1sJ5BhU3_GhaV51Jd8r7jfR5-vikxNReVrgT4opQ&oe=6AAE1EA9",
    "shortCode": "DUFADW6AB6G",
    "url": "https://www.instagram.com/p/DUFADW6AB6G/",
    "instagramUrl": "https://www.instagram.com/p/DUFADW6AB6G/",
    "rating": 5,
    "reviewsCount": 36,
    "commentsCount": 4,
    "tags": [
      "sunset dreams",
      "descuentos",
      "2x1 en coctelería",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-08",
    "name": "Cosecha del Mar",
    "brand": "Cosecha del Mar",
    "category": "descuentos",
    "categoryBadge": "🔥 Descuento Especial",
    "benefitType": "Descuento Pescadería",
    "discount": "10% de descuento en salmón ahumado y patés",
    "status": "Activo",
    "schedule": "Válido compras presenciales",
    "howToRedeem": "Decir código 'COSECHAJOSÉ' en caja de Decher 161.",
    "shortDesc": "Descuento Pescadería · Válido compras presenciales",
    "personalTip": "10% de descuento en salmón ahumado y patés. Canje: Decir código 'COSECHAJOSÉ' en caja de Decher 161.",
    "fullCaption": "🎬 Dándolo todo en las grabaciones!! \nFuí a @tiendascosechadelmar a buscar los mejores salmones para hacer la receta viral: Torta de sushi 🍣\n📍Decher 161 Puerto Varas\n\n#puertovaraschile #puertovaras",
    "image": "thumbs/thumb_DVSGMvtAAoZ.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://scontent-hou1-1.cdninstagram.com/o1/v/t2/f2/m86/AQMDLfMqyExJuG4dkVB_nR6VsSVAikRnxi4rfsFobqyJ6c4l46j9pBdfQu-0XowgBmX8RZ3t6xBeU44HRWsvKdqYXm9x6QRVW0FopXQ.mp4?_nc_cat=110&_nc_sid=5e9851&_nc_ht=scontent-hou1-1.cdninstagram.com&_nc_ohc=teLZf39BawsQ7kNvwFD0oHp&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTc5NTE1NDA3NDgwOTc3MDYsImFzc2V0X2FnZV9kYXlzIjoyMDEsInZpX3VzZWNhc2VfaWQiOjEwODI3LCJkdXJhdGlvbl9zIjoxNiwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=ed187559e469770&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9FRjQ5RUI2Qzc5QTM4NUI2OENDQTA5NjI4RDQ5NkM4NF92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzk4NDNFMzM3NzgxMTMxNEExODY3OTE3MzI5M0QzQkIzX2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbU4rCXmbXjPxUCKAJDMywXQDBdsi0OVgQYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZZapAQA&_nc_gid=yH-k2ViCa7dxYNNP2TFEWw&_nc_ss=7a22e&_nc_zt=28&oh=00_AQIHJsZob5HyKHDF6MwKCrj_omyhc-cfh8MwyOinQJx80A&oe=6AAE3A9B",
    "shortCode": "DVSGMvtAAoZ",
    "url": "https://www.instagram.com/p/DVSGMvtAAoZ/",
    "instagramUrl": "https://www.instagram.com/p/DVSGMvtAAoZ/",
    "rating": 5,
    "reviewsCount": 62,
    "commentsCount": 6,
    "tags": [
      "cosecha del mar",
      "descuentos",
      "descuento pescadería",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-09",
    "name": "Alquimia RestoBar",
    "brand": "Alquimia RestoBar",
    "category": "productos",
    "categoryBadge": "🎁 Regalo por Compra",
    "benefitType": "Café de Regalo",
    "discount": "Café espresso o americano gratis con tu brunch",
    "status": "Activo",
    "schedule": "Lunes a Viernes 09:00 a 12:00",
    "howToRedeem": "Mencionar a Datitos de la Jose al pedir tu desayuno.",
    "shortDesc": "Café de Regalo · Lunes a Viernes 09:00 a 12:00",
    "personalTip": "Café espresso o americano gratis con tu brunch. Canje: Mencionar a Datitos de la Jose al pedir tu desayuno.",
    "fullCaption": "☕️🍸 ¿Ya conoces @alquimia.puertovaras ?\n📍 Decher 450 Galpón Aire Puro Puerto Varas\n\n#restobar #cafeteria #tragosdeautor #puertovaraschile",
    "image": "thumbs/thumb_DYVU6YZPeqN.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://instagram.fcdg2-1.fna.fbcdn.net/o1/v/t2/f2/m86/AQNk9BLYx6qAsW-BDlfHbSaKOpLLbvrCkbh0co2UVZMbuozP-e_S6tZ3v_N0dRUmJHLHtkLzRaaQGfSor0ocq9GrzTj6ze05ABwVaEw.mp4?_nc_cat=101&_nc_oc=Adqqn5mBxTHhryJPzeyE33lzwv9LBOIN_tzLJj19_ow_Jmbn8RWEwqZ2ddiqBTa2zpsE_HuguG3WZu4wCxkR9kwR&_nc_sid=5e9851&_nc_ht=instagram.fcdg2-1.fna.fbcdn.net&_nc_ohc=M0WnKO6Z24AQ7kNvwEl4fh9&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MTY1NzM5MjI4MjE2MTQ0MSwiYXNzZXRfYWdlX2RheXMiOjEyNSwidmlfdXNlY2FzZV9pZCI6MTA4MjcsImR1cmF0aW9uX3MiOjMwLCJ1cmxnZW5fc291cmNlIjoid3d3In0%3D&ccb=17-1&vs=66bb13be7fb708ec&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9GRjQ3Mzg4NzQ3QkMyODFGQjY5QzRFMzk0MTlDODFBQl92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzc5NDhGRDMyNEE5MjY3QzgxMkE2MjIwOUUxRDc5NTk5X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACbCxNrj9tjxBRUCKAJDMywXQD4AAAAAAAAYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZZapAQA&_nc_gid=959-AwgCTqWVzHfdEekyTQ&_nc_ss=7a22e&_nc_map=urlgen_bucketless&_nc_zt=28&oh=00_AQKk-Ykex_Jbsc8UeIlyEmGhn-WvmWZeBg09Q2iTmLdwsg&oe=6AAE175E",
    "shortCode": "DYVU6YZPeqN",
    "url": "https://www.instagram.com/p/DYVU6YZPeqN/",
    "instagramUrl": "https://www.instagram.com/p/DYVU6YZPeqN/",
    "rating": 5,
    "reviewsCount": 134,
    "commentsCount": 3,
    "tags": [
      "alquimia restobar",
      "productos",
      "café de regalo",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-10",
    "name": "Brücken Puerto Varas",
    "brand": "Brücken Puerto Varas",
    "category": "productos",
    "categoryBadge": "🎁 Regalo por Compra",
    "benefitType": "Schop de Regalo",
    "discount": "1 schop artesanal de regalo por cada tabla familiar",
    "status": "Activo",
    "schedule": "Martes y Miércoles karaoke",
    "howToRedeem": "Presentar el Reel de Jose en el teléfono.",
    "shortDesc": "Schop de Regalo · Martes y Miércoles karaoke",
    "personalTip": "1 schop artesanal de regalo por cada tabla familiar. Canje: Presentar el Reel de Jose en el teléfono.",
    "fullCaption": "🎸🍔🍸¡¡Hasta con escenario!! Siii, en @bruckenpv puedes venir a comer ricas hamburguesas, tomar el micrófono y ponerte a cantar. Además puedes realizar tus celebraciones y reuniones ya que tienen 3 ambientes para lo que necesites.\n📍Está en pleno centro de Puerto Varas a un costado del Mall Paseo. Pio Nono 427\n\n#hamburguesasdeautor #karaoke #restobar #hamburgueseria #menudiario #puertovaras #puertovaraschile",
    "image": "thumbs/thumb_C8MyNmsuHN-.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://instagram.fssa2-1.fna.fbcdn.net/o1/v/t2/f2/m82/AQMMM1S-cmrtKi_wDJxL1EFI-zVTdyq03AsF3UjqhTPfF65WAqh2pVB2Cv5sLrZPtz0FLKfJbJQpx7uzggl7hIrGwJSTo1yM7Rew5-8.mp4?_nc_cat=106&_nc_oc=Adoq6i9hVY9rlrt3OcXLnUghGV3nIeMlDXWj1_YQwZdHLroozXeJWQxOq8Cvrxa34Vo&_nc_sid=5e9851&_nc_ht=instagram.fssa2-1.fna.fbcdn.net&_nc_ohc=9TZsvEwWxTQQ7kNvwERn1Hh&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6NDM0Nzc4MzY2MTQ3MzQwLCJhc3NldF9hZ2VfZGF5cyI6ODI1LCJ2aV91c2VjYXNlX2lkIjoxMDA5OSwiZHVyYXRpb25fcyI6MjEsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=e34f9cb1e28701f9&_nc_vs=HBksFQIYT2lnX3hwdl9yZWVsc19wZXJtYW5lbnRfcHJvZC9DRjQ3NTg0QzRDMTkzNkRGOTU2NzkyQjZFODNCNTE5OF92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYRmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC84Mzk2MTc0NDQ2OTAyOTNfMjE4ODE2NDY2OTk4NTU0NzczMy5tcDQVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmmOyPobfbxQEVAigCQzMsF0A1GZmZmZmaGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHX-B2XmnQEA&_nc_gid=D4GTRjJr97q3k5PrQtv7Sg&_nc_ss=7a22e&_nc_zt=28&oh=00_AQKCMM4rDxPUyTtleAeiG8AuYrGTQm-XSwvQQ_x4tmB68w&oe=6AAE2D8B",
    "shortCode": "C8MyNmsuHN-",
    "url": "https://www.instagram.com/p/C8MyNmsuHN-/",
    "instagramUrl": "https://www.instagram.com/p/C8MyNmsuHN-/",
    "rating": 5,
    "reviewsCount": 143,
    "commentsCount": 13,
    "tags": [
      "brücken puerto varas",
      "productos",
      "schop de regalo",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-11",
    "name": "Loica Moda Circular",
    "brand": "Loica Moda Circular",
    "category": "descuentos",
    "categoryBadge": "🔥 Descuento Especial",
    "benefitType": "Descuento en Ropa",
    "discount": "20% de descuento en tu segunda prenda vintage",
    "status": "Activo",
    "schedule": "Todo el mes",
    "howToRedeem": "Mencionar que vienes de Instagram.",
    "shortDesc": "Descuento en Ropa · Todo el mes",
    "personalTip": "20% de descuento en tu segunda prenda vintage. Canje: Mencionar que vienes de Instagram.",
    "fullCaption": "🧥 ¡¡Sustentabilidad Textil!!\nLa verdad es que ya hace un tiempo estoy fanática de reutilizar y comprar en lugares donde la 2da vida de los productos sea la primera opción.\n👕 En @loica_pv encuentras un montón de ropa fantástica!! \n📍En la nueva tienda que está en Nuestra Señora del Carmen 1060, hay ropa de adulto también. Yo me llevé 2 chaquetas maravillosas y ultra baratas!!!\n.\n.\n#ropasustentable #sustentabilidadtextil #sustentable #segundamano #segundavida #reciclajetextil #yoapoyoalaspymes #puertovaras #regiondeloslagos",
    "image": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://instagram.fsyd14-1.fna.fbcdn.net/o1/v/t16/f2/m69/AQOfd5qzx8ETzEPpmoO3tlXNT9QAeDgzM-2vM-k6Qxw4eqvsJkERxY8CkYBHckL4CLHU29_bxEo-acBU4xH_YakH.mp4?strext=1&_nc_cat=107&_nc_oc=Ado0iFWfkawkuMKacEpPoiLns8ivzaV2x_rlCCeRmnZ5-plNbBy5NbWjz_4KdplQdio&_nc_sid=5e9851&_nc_ht=instagram.fsyd14-1.fna.fbcdn.net&_nc_ohc=4_dhVw0PcNUQ7kNvwGiXK_G&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uSUdUVi5DMy43MjAuZGFzaF9iYXNlbGluZV8xX3YxIiwieHB2X2Fzc2V0X2lkIjo3NTQ2Njc3NzU1ODU3NDIsImFzc2V0X2FnZV9kYXlzIjoxNTQyLCJ2aV91c2VjYXNlX2lkIjoxMDE0NSwiZHVyYXRpb25fcyI6OCwidXJsZ2VuX3NvdXJjZSI6Ind3dyJ9&ccb=17-1&vs=b0b360be52dc2363&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HRGI3U3hIeDJUZm5Tb2tDQUFRNmhIWjNKU04wYnZWQkFBQUYVAALIARIAFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HTzNDWEJGNk9XQ3lwbndEQUJmdUZHcmxvZVJVYnZWQkFBQUYVAgLIARIAKAAYABsCiAd1c2Vfb2lsATEScHJvZ3Jlc3NpdmVfcmVjaXBlATEVAAAmnLf_irmX1wIVAigCQzMsF0AgzMzMzMzNGBJkYXNoX2Jhc2VsaW5lXzFfdjERAHXsB2XCngEA&_nc_gid=Pb0clAne2mt5oelOXL6DdA&_nc_ss=7a22e&_nc_zt=28&oh=00_AQLYftSMxugmxVAJxoylA1fG9bqFrvNhv9IFrh9uMALJ2A&oe=6AB20D5D",
    "shortCode": "CfXMNdJllkF",
    "url": "https://www.instagram.com/p/CfXMNdJllkF/",
    "instagramUrl": "https://www.instagram.com/p/CfXMNdJllkF/",
    "rating": 5,
    "reviewsCount": 46,
    "commentsCount": 4,
    "tags": [
      "loica moda circular",
      "descuentos",
      "descuento en ropa",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  },
  {
    "id": "PROMO-12",
    "name": "Refugio Mayapehue",
    "brand": "Refugio Mayapehue",
    "category": "descuentos",
    "categoryBadge": "🔥 Descuento Especial",
    "benefitType": "Descuento Hospedaje",
    "discount": "15% OFF en estadías de 2+ noches en temporada baja",
    "status": "Activo",
    "schedule": "Abril a Noviembre",
    "howToRedeem": "Escribir al WhatsApp directo con código #DATITOSCHONCHI.",
    "shortDesc": "Descuento Hospedaje · Abril a Noviembre",
    "personalTip": "15% OFF en estadías de 2+ noches en temporada baja. Canje: Escribir al WhatsApp directo con código #DATITOSCHONCHI.",
    "fullCaption": "Un maravilloso descubrimiento en Chiloé @refugio.mayapehue donde todo es una verdadera postal.\n• Lo puedes encontrar por Airbnb o directamente con Pedro y Claudia al WhatsApp +5699299174\n📍Camino Miraflores, km 3 Chonchi / Chiloé (a 40 minutos del centro de Castro)\n\n#chiloe #castrochiloe #chonchi",
    "image": "thumbs/thumb_DdPtGFQg88W.jpg",
    "fallbackImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
    "videoUrl": "https://instagram.flhr13-1.fna.fbcdn.net/o1/v/t16/f2/m84/AQPvsdKbJA689t7Pj1GnnUDX46oCBSq_BI6ruKyBvJqJ8Gi4Ye0P8yzRqLlT6RzQkTcQ7j6V4Gbsewa9plnbM1uNDXVMYPgLBYjl1Dw.mp4?_nc_cat=108&_nc_oc=Adrgf48WMffQxk8aNR1YAHwv_Kg70h-cnTJKoUrXn4_BXr3eO_6EVIoUAMXK6K8IrHY&_nc_sid=5e9851&_nc_ht=instagram.flhr13-1.fna.fbcdn.net&_nc_ohc=-SnCewGw59IQ7kNvwHnFuG9&efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSIsInhwdl9hc3NldF9pZCI6MjgzNjMzNDA4MzMzMjA0NDksImFzc2V0X2FnZV9kYXlzIjozLCJ2aV91c2VjYXNlX2lkIjoxMDgyNywiZHVyYXRpb25fcyI6MzYsInVybGdlbl9zb3VyY2UiOiJ3d3cifQ%3D%3D&ccb=17-1&vs=486016cba6f4d6e7&_nc_vs=HBksFQIYTGlnX2JhY2tmaWxsX3RpbWVsaW5lX3ZvZC8wQjQzQ0ZBRURGNTE0M0IwM0E4MjgzOEQ1NTA1QUU5RV92aWRlb19kYXNoaW5pdC5tcDQVAALIARIAFQIYUWlnX3hwdl9wbGFjZW1lbnRfcGVybWFuZW50X3YyLzg0NDhGMjAzODJGMEI0QTJGRTIwNUJCMzUzQjQxOUI0X2F1ZGlvX2Rhc2hpbml0Lm1wNBUCAsgBEgAoABgAGwKIB3VzZV9vaWwBMRJwcm9ncmVzc2l2ZV9yZWNpcGUBMRUAACaCuJvw3JPiZBUCKAJDMywXQEJmZmZmZmYYEmRhc2hfYmFzZWxpbmVfMV92MREAdf4HZZapAQA&_nc_gid=ep39lSCPWYY2JN0sa3fkLA&_nc_zt=28&_nc_ss=7a22e&oh=00_AQLETVmi601xXnM5ac-FP2JoXEYrSopE1gPfsupZKzv6Sg&oe=6AAE4094",
    "shortCode": "DdPtGFQg88W",
    "url": "https://www.instagram.com/p/DdPtGFQg88W/",
    "instagramUrl": "https://www.instagram.com/p/DdPtGFQg88W/",
    "rating": 5,
    "reviewsCount": 366,
    "commentsCount": 15,
    "tags": [
      "refugio mayapehue",
      "descuentos",
      "descuento hospedaje",
      "promocion",
      "descuento",
      "puerto varas"
    ]
  }
];
const PLACES_DATA = PROMOS_DATA;
const initialPlaces = PROMOS_DATA;
const initialPromos = PROMOS_DATA;

if (typeof window !== 'undefined') {
  window.PROMOS_DATA = PROMOS_DATA;
  window.PLACES_DATA = PROMOS_DATA;
  window.initialPlaces = PROMOS_DATA;
  window.initialPromos = PROMOS_DATA;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PROMOS_DATA, PLACES_DATA, initialPlaces, initialPromos };
}
