// js/reels-data.js - Catalogo oficial desde Datitos_reales.xlsx
// Hotel:22 Restaurante:35 Cafe:10 Panorama:16 Total:83

const REELS_DATA = [
  {
    "id": 1,
    "shortcode": "DVPWP04j4aq",
    "igUrl": "https://www.instagram.com/reel/DVPWP04j4aq/",
    "thumbUrl": "https://www.instagram.com/p/DVPWP04j4aq/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 2,
    "shortcode": "DUXC2OggLTC",
    "igUrl": "https://www.instagram.com/reel/DUXC2OggLTC/",
    "thumbUrl": "https://www.instagram.com/p/DUXC2OggLTC/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 3,
    "shortcode": "DURRUl4j00E",
    "igUrl": "https://www.instagram.com/reel/DURRUl4j00E/",
    "thumbUrl": "https://www.instagram.com/p/DURRUl4j00E/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 4,
    "shortcode": "DRieRJpD8ga",
    "igUrl": "https://www.instagram.com/reel/DRieRJpD8ga/",
    "thumbUrl": "https://www.instagram.com/p/DRieRJpD8ga/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 5,
    "shortcode": "DMgjOk3PULT",
    "igUrl": "https://www.instagram.com/reel/DMgjOk3PULT/",
    "thumbUrl": "https://www.instagram.com/p/DMgjOk3PULT/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 6,
    "shortcode": "DMO2XZqgAv7",
    "igUrl": "https://www.instagram.com/reel/DMO2XZqgAv7/",
    "thumbUrl": "https://www.instagram.com/p/DMO2XZqgAv7/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 7,
    "shortcode": "DI2AjSZPe8b",
    "igUrl": "https://www.instagram.com/reel/DI2AjSZPe8b/",
    "thumbUrl": "https://www.instagram.com/p/DI2AjSZPe8b/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 8,
    "shortcode": "DIxasMLAr4W",
    "igUrl": "https://www.instagram.com/reel/DIxasMLAr4W/",
    "thumbUrl": "https://www.instagram.com/p/DIxasMLAr4W/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 9,
    "shortcode": "DIg8vHpA9A0",
    "igUrl": "https://www.instagram.com/reel/DIg8vHpA9A0/",
    "thumbUrl": "https://www.instagram.com/p/DIg8vHpA9A0/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 10,
    "shortcode": "DIF0YQjgzZ6",
    "igUrl": "https://www.instagram.com/reel/DIF0YQjgzZ6/",
    "thumbUrl": "https://www.instagram.com/p/DIF0YQjgzZ6/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 11,
    "shortcode": "DHrIE4RPTD0",
    "igUrl": "https://www.instagram.com/reel/DHrIE4RPTD0/",
    "thumbUrl": "https://www.instagram.com/p/DHrIE4RPTD0/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 12,
    "shortcode": "DHZhDAzPzWl",
    "igUrl": "https://www.instagram.com/reel/DHZhDAzPzWl/",
    "thumbUrl": "https://www.instagram.com/p/DHZhDAzPzWl/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 13,
    "shortcode": "DHT3z_KvxTF",
    "igUrl": "https://www.instagram.com/reel/DHT3z_KvxTF/",
    "thumbUrl": "https://www.instagram.com/p/DHT3z_KvxTF/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 14,
    "shortcode": "DHJdBAcgxXF",
    "igUrl": "https://www.instagram.com/reel/DHJdBAcgxXF/",
    "thumbUrl": "https://www.instagram.com/p/DHJdBAcgxXF/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 15,
    "shortcode": "DBmZzFGyEn1",
    "igUrl": "https://www.instagram.com/reel/DBmZzFGyEn1/",
    "thumbUrl": "https://www.instagram.com/p/DBmZzFGyEn1/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 16,
    "shortcode": "C-wDBXtu6Us",
    "igUrl": "https://www.instagram.com/reel/C-wDBXtu6Us/",
    "thumbUrl": "https://www.instagram.com/p/C-wDBXtu6Us/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 17,
    "shortcode": "C8viWkou1y6",
    "igUrl": "https://www.instagram.com/reel/C8viWkou1y6/",
    "thumbUrl": "https://www.instagram.com/p/C8viWkou1y6/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 18,
    "shortcode": "C8dC4gFOpV2",
    "igUrl": "https://www.instagram.com/reel/C8dC4gFOpV2/",
    "thumbUrl": "https://www.instagram.com/p/C8dC4gFOpV2/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 19,
    "shortcode": "C67cjTcujYF",
    "igUrl": "https://www.instagram.com/reel/C67cjTcujYF/",
    "thumbUrl": "https://www.instagram.com/p/C67cjTcujYF/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 20,
    "shortcode": "C5xFK0sOYLn",
    "igUrl": "https://www.instagram.com/reel/C5xFK0sOYLn/",
    "thumbUrl": "https://www.instagram.com/p/C5xFK0sOYLn/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 21,
    "shortcode": "C3oOZL5OXWS",
    "igUrl": "https://www.instagram.com/reel/C3oOZL5OXWS/",
    "thumbUrl": "https://www.instagram.com/p/C3oOZL5OXWS/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 22,
    "shortcode": "C2D-y1_OH3Z",
    "igUrl": "https://www.instagram.com/reel/C2D-y1_OH3Z/",
    "thumbUrl": "https://www.instagram.com/p/C2D-y1_OH3Z/media/?size=m",
    "title": "Hotel & Cabana · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Hotel & Cabana",
    "filter": "cabanas",
    "badge": "Alojamiento",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 23,
    "shortcode": "DZV5HhAgwnz",
    "igUrl": "https://www.instagram.com/reel/DZV5HhAgwnz/",
    "thumbUrl": "https://www.instagram.com/p/DZV5HhAgwnz/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 24,
    "shortcode": "DY3biBSgfid",
    "igUrl": "https://www.instagram.com/reel/DY3biBSgfid/",
    "thumbUrl": "https://www.instagram.com/p/DY3biBSgfid/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 25,
    "shortcode": "DYVU6YZPeqN",
    "igUrl": "https://www.instagram.com/reel/DYVU6YZPeqN/",
    "thumbUrl": "https://www.instagram.com/p/DYVU6YZPeqN/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 26,
    "shortcode": "DX0TQJHAoHN",
    "igUrl": "https://www.instagram.com/reel/DX0TQJHAoHN/",
    "thumbUrl": "https://www.instagram.com/p/DX0TQJHAoHN/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 27,
    "shortcode": "DXVyDxkgHlz",
    "igUrl": "https://www.instagram.com/reel/DXVyDxkgHlz/",
    "thumbUrl": "https://www.instagram.com/p/DXVyDxkgHlz/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 28,
    "shortcode": "DXGM7MYAF1G",
    "igUrl": "https://www.instagram.com/reel/DXGM7MYAF1G/",
    "thumbUrl": "https://www.instagram.com/p/DXGM7MYAF1G/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 29,
    "shortcode": "DWNEEsfj2-2",
    "igUrl": "https://www.instagram.com/reel/DWNEEsfj2-2/",
    "thumbUrl": "https://www.instagram.com/p/DWNEEsfj2-2/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 30,
    "shortcode": "DWH1e35DxJC",
    "igUrl": "https://www.instagram.com/reel/DWH1e35DxJC/",
    "thumbUrl": "https://www.instagram.com/p/DWH1e35DxJC/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 31,
    "shortcode": "DUornaXj7zc",
    "igUrl": "https://www.instagram.com/reel/DUornaXj7zc/",
    "thumbUrl": "https://www.instagram.com/p/DUornaXj7zc/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 32,
    "shortcode": "DRkgHLWj-nB",
    "igUrl": "https://www.instagram.com/reel/DRkgHLWj-nB/",
    "thumbUrl": "https://www.instagram.com/p/DRkgHLWj-nB/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 33,
    "shortcode": "DQ-yYeqANoO",
    "igUrl": "https://www.instagram.com/reel/DQ-yYeqANoO/",
    "thumbUrl": "https://www.instagram.com/p/DQ-yYeqANoO/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 34,
    "shortcode": "DOCtqmcgBCR",
    "igUrl": "https://www.instagram.com/reel/DOCtqmcgBCR/",
    "thumbUrl": "https://www.instagram.com/p/DOCtqmcgBCR/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 35,
    "shortcode": "DL_d9BmgJlB",
    "igUrl": "https://www.instagram.com/reel/DL_d9BmgJlB/",
    "thumbUrl": "https://www.instagram.com/p/DL_d9BmgJlB/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 36,
    "shortcode": "DL8gq-6vF9n",
    "igUrl": "https://www.instagram.com/reel/DL8gq-6vF9n/",
    "thumbUrl": "https://www.instagram.com/p/DL8gq-6vF9n/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 37,
    "shortcode": "DLtTAEYg2KY",
    "igUrl": "https://www.instagram.com/reel/DLtTAEYg2KY/",
    "thumbUrl": "https://www.instagram.com/p/DLtTAEYg2KY/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 38,
    "shortcode": "DKnnwfrPSl5",
    "igUrl": "https://www.instagram.com/reel/DKnnwfrPSl5/",
    "thumbUrl": "https://www.instagram.com/p/DKnnwfrPSl5/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 39,
    "shortcode": "DJw4IABgfOe",
    "igUrl": "https://www.instagram.com/reel/DJw4IABgfOe/",
    "thumbUrl": "https://www.instagram.com/p/DJw4IABgfOe/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 40,
    "shortcode": "DJNhUj-v0K0",
    "igUrl": "https://www.instagram.com/reel/DJNhUj-v0K0/",
    "thumbUrl": "https://www.instagram.com/p/DJNhUj-v0K0/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 41,
    "shortcode": "DJAbcjqvDLk",
    "igUrl": "https://www.instagram.com/reel/DJAbcjqvDLk/",
    "thumbUrl": "https://www.instagram.com/p/DJAbcjqvDLk/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 42,
    "shortcode": "DIxasMLAr4W",
    "igUrl": "https://www.instagram.com/reel/DIxasMLAr4W/",
    "thumbUrl": "https://www.instagram.com/p/DIxasMLAr4W/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 43,
    "shortcode": "DImjI_APekl",
    "igUrl": "https://www.instagram.com/reel/DImjI_APekl/",
    "thumbUrl": "https://www.instagram.com/p/DImjI_APekl/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 44,
    "shortcode": "DIVH8fWAVEh",
    "igUrl": "https://www.instagram.com/reel/DIVH8fWAVEh/",
    "thumbUrl": "https://www.instagram.com/p/DIVH8fWAVEh/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 45,
    "shortcode": "DHJdBAcgxXF",
    "igUrl": "https://www.instagram.com/reel/DHJdBAcgxXF/",
    "thumbUrl": "https://www.instagram.com/p/DHJdBAcgxXF/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 46,
    "shortcode": "DFu7YUSOim6",
    "igUrl": "https://www.instagram.com/reel/DFu7YUSOim6/",
    "thumbUrl": "https://www.instagram.com/p/DFu7YUSOim6/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 47,
    "shortcode": "DD7Zgyzu7tb",
    "igUrl": "https://www.instagram.com/reel/DD7Zgyzu7tb/",
    "thumbUrl": "https://www.instagram.com/p/DD7Zgyzu7tb/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 48,
    "shortcode": "C8qEKixOQCF",
    "igUrl": "https://www.instagram.com/reel/C8qEKixOQCF/",
    "thumbUrl": "https://www.instagram.com/p/C8qEKixOQCF/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 49,
    "shortcode": "C8MyNmsuHN-",
    "igUrl": "https://www.instagram.com/reel/C8MyNmsuHN-/",
    "thumbUrl": "https://www.instagram.com/p/C8MyNmsuHN-/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 50,
    "shortcode": "C8JVQBLuLM0",
    "igUrl": "https://www.instagram.com/reel/C8JVQBLuLM0/",
    "thumbUrl": "https://www.instagram.com/p/C8JVQBLuLM0/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 51,
    "shortcode": "C41fyu6OTZK",
    "igUrl": "https://www.instagram.com/reel/C41fyu6OTZK/",
    "thumbUrl": "https://www.instagram.com/p/C41fyu6OTZK/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 52,
    "shortcode": "C3_iYbzuEJ5",
    "igUrl": "https://www.instagram.com/reel/C3_iYbzuEJ5/",
    "thumbUrl": "https://www.instagram.com/p/C3_iYbzuEJ5/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 53,
    "shortcode": "C2swrqbun-c",
    "igUrl": "https://www.instagram.com/reel/C2swrqbun-c/",
    "thumbUrl": "https://www.instagram.com/p/C2swrqbun-c/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 54,
    "shortcode": "C2TRK_tuJPH",
    "igUrl": "https://www.instagram.com/reel/C2TRK_tuJPH/",
    "thumbUrl": "https://www.instagram.com/p/C2TRK_tuJPH/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 55,
    "shortcode": "C2OPeaJuMaB",
    "igUrl": "https://www.instagram.com/reel/C2OPeaJuMaB/",
    "thumbUrl": "https://www.instagram.com/p/C2OPeaJuMaB/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 56,
    "shortcode": "C2I_hEUOpDq",
    "igUrl": "https://www.instagram.com/reel/C2I_hEUOpDq/",
    "thumbUrl": "https://www.instagram.com/p/C2I_hEUOpDq/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 57,
    "shortcode": "CruRRV4NK-Q",
    "igUrl": "https://www.instagram.com/reel/CruRRV4NK-Q/",
    "thumbUrl": "https://www.instagram.com/p/CruRRV4NK-Q/media/?size=m",
    "title": "Restaurante · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Restaurante",
    "filter": "restaurante",
    "badge": "Gastronomia",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 58,
    "shortcode": "Db9KoGTP380",
    "igUrl": "https://www.instagram.com/reel/Db9KoGTP380/",
    "thumbUrl": "https://www.instagram.com/p/Db9KoGTP380/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 59,
    "shortcode": "DYJOGWHghni",
    "igUrl": "https://www.instagram.com/reel/DYJOGWHghni/",
    "thumbUrl": "https://www.instagram.com/p/DYJOGWHghni/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 60,
    "shortcode": "DRvES5UD7y5",
    "igUrl": "https://www.instagram.com/reel/DRvES5UD7y5/",
    "thumbUrl": "https://www.instagram.com/p/DRvES5UD7y5/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 61,
    "shortcode": "DQ5mAlxgBZT",
    "igUrl": "https://www.instagram.com/reel/DQ5mAlxgBZT/",
    "thumbUrl": "https://www.instagram.com/p/DQ5mAlxgBZT/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 62,
    "shortcode": "DO6-OFRDa8M",
    "igUrl": "https://www.instagram.com/reel/DO6-OFRDa8M/",
    "thumbUrl": "https://www.instagram.com/p/DO6-OFRDa8M/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 63,
    "shortcode": "DM3nQ_FPSJZ",
    "igUrl": "https://www.instagram.com/reel/DM3nQ_FPSJZ/",
    "thumbUrl": "https://www.instagram.com/p/DM3nQ_FPSJZ/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 64,
    "shortcode": "DELKBfjyezY",
    "igUrl": "https://www.instagram.com/reel/DELKBfjyezY/",
    "thumbUrl": "https://www.instagram.com/p/DELKBfjyezY/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 65,
    "shortcode": "C-B2ZBpO6OK",
    "igUrl": "https://www.instagram.com/reel/C-B2ZBpO6OK/",
    "thumbUrl": "https://www.instagram.com/p/C-B2ZBpO6OK/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 66,
    "shortcode": "C9ykiPCObmj",
    "igUrl": "https://www.instagram.com/reel/C9ykiPCObmj/",
    "thumbUrl": "https://www.instagram.com/p/C9ykiPCObmj/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 67,
    "shortcode": "C7VG9QbO2-E",
    "igUrl": "https://www.instagram.com/reel/C7VG9QbO2-E/",
    "thumbUrl": "https://www.instagram.com/p/C7VG9QbO2-E/media/?size=m",
    "title": "Cafe & Kuchen · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Cafe & Kuchen",
    "filter": "cafe",
    "badge": "Cafe",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 68,
    "shortcode": "DbWZ18DP2kn",
    "igUrl": "https://www.instagram.com/reel/DbWZ18DP2kn/",
    "thumbUrl": "https://www.instagram.com/p/DbWZ18DP2kn/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 69,
    "shortcode": "DalyhcfAlE9",
    "igUrl": "https://www.instagram.com/reel/DalyhcfAlE9/",
    "thumbUrl": "https://www.instagram.com/p/DalyhcfAlE9/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 70,
    "shortcode": "DUg-BnLD8Tr",
    "igUrl": "https://www.instagram.com/reel/DUg-BnLD8Tr/",
    "thumbUrl": "https://www.instagram.com/p/DUg-BnLD8Tr/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 71,
    "shortcode": "DRSgBkiCTvk",
    "igUrl": "https://www.instagram.com/reel/DRSgBkiCTvk/",
    "thumbUrl": "https://www.instagram.com/p/DRSgBkiCTvk/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 72,
    "shortcode": "DQS5NHrgNDv",
    "igUrl": "https://www.instagram.com/reel/DQS5NHrgNDv/",
    "thumbUrl": "https://www.instagram.com/p/DQS5NHrgNDv/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 73,
    "shortcode": "DQFEylPAH-4",
    "igUrl": "https://www.instagram.com/reel/DQFEylPAH-4/",
    "thumbUrl": "https://www.instagram.com/p/DQFEylPAH-4/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 74,
    "shortcode": "DMO2XZqgAv7",
    "igUrl": "https://www.instagram.com/reel/DMO2XZqgAv7/",
    "thumbUrl": "https://www.instagram.com/p/DMO2XZqgAv7/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 75,
    "shortcode": "DKDDfmjPUFV",
    "igUrl": "https://www.instagram.com/reel/DKDDfmjPUFV/",
    "thumbUrl": "https://www.instagram.com/p/DKDDfmjPUFV/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 76,
    "shortcode": "DIg8vHpA9A0",
    "igUrl": "https://www.instagram.com/reel/DIg8vHpA9A0/",
    "thumbUrl": "https://www.instagram.com/p/DIg8vHpA9A0/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 77,
    "shortcode": "DY5H8I8vtaL",
    "igUrl": "https://www.instagram.com/reel/DY5H8I8vtaL/",
    "thumbUrl": "https://www.instagram.com/p/DY5H8I8vtaL/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 78,
    "shortcode": "DccG79EvATQ",
    "igUrl": "https://www.instagram.com/reel/DccG79EvATQ/",
    "thumbUrl": "https://www.instagram.com/p/DccG79EvATQ/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 79,
    "shortcode": "DcNGkHBAS56",
    "igUrl": "https://www.instagram.com/reel/DcNGkHBAS56/",
    "thumbUrl": "https://www.instagram.com/p/DcNGkHBAS56/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 80,
    "shortcode": "DbgvHJ2vJAy",
    "igUrl": "https://www.instagram.com/reel/DbgvHJ2vJAy/",
    "thumbUrl": "https://www.instagram.com/p/DbgvHJ2vJAy/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 81,
    "shortcode": "Db6v33qAjZQ",
    "igUrl": "https://www.instagram.com/reel/Db6v33qAjZQ/",
    "thumbUrl": "https://www.instagram.com/p/Db6v33qAjZQ/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 82,
    "shortcode": "Dbt2PD-AwO1",
    "igUrl": "https://www.instagram.com/reel/Dbt2PD-AwO1/",
    "thumbUrl": "https://www.instagram.com/p/Dbt2PD-AwO1/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  },
  {
    "id": 83,
    "shortcode": "DbjS5tLPT6W",
    "igUrl": "https://www.instagram.com/reel/DbjS5tLPT6W/",
    "thumbUrl": "https://www.instagram.com/p/DbjS5tLPT6W/media/?size=m",
    "title": "Panorama & Dato · @datitosdelajose",
    "lugar": "Puerto Varas · Region de Los Lagos",
    "categoria": "Panorama & Dato",
    "filter": "aventura",
    "badge": "Panorama",
    "desc": "Recomendacion comprobada personalmente por Maria Jose Ibanez Walker (@datitosdelajose).",
    "detalles": "Visita el reel en Instagram para mas informacion.",
    "waLink": "https://wa.me/56979430387?text=Hola!%20Vi%20el%20video%20de%20%40datitosdelajose%20y%20quiero%20consultar.",
    "airbnbLink": "",
    "igHandle": "@datitosdelajose"
  }
];

if(typeof module!=='undefined') module.exports={REELS_DATA};
