// reels-data.js - Catálogo Oficial de Reels de María José / @datitosdelajose
// Creadora: María José Ibáñez (@datitosdelajose) · Puerto Varas, Región de Los Lagos
// Datos y recomendaciones 100% comprobadas en terreno con enlaces a Airbnb, WhatsApp y geolocalización.

const REELS_DATA = [
  {
    id: 1,
    shortcode: "DVPWP04j4aq",
    titulo: "Camping Suyai Ensenada · Acceso Directo al Lago",
    lugar: "Camping Suyai Ensenada",
    handle: "@datitosdelajose • @campingsuyaiensenada",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Camping",
    vistas: "Acceso al Lago",
    descripcion: "¿Una escapadita? Te dejo 3 opciones en Camping Suyai: Camping, sitios para picnic/asado y mini cabaña acogedora. Todos con bajada y acceso directo a la playa del lago Llanquihue.",
    detalles: " Por orden de llegada. No requiere reserva previa para picnic.\n• Km 42 frente a Copec de Ensenada, Puerto Varas.",
    direccion: "Ruta 225 Km 42, frente a Copec, Ensenada, Puerto Varas",
    whatsapp: "+56968507827",
    whatsappUrl: "https://wa.me/56968507827?text=Hola!%20Vi%20el%20video%20de%20Mamá%20Santi%20(@datitosdelajose)%20y%20quiero%20consultar%20por%20disponibilidad.",
    airbnbUrl: "https://www.airbnb.cl/s/Ensenada--Los-Lagos--Chile/homes?query=Ensenada%20Puerto%20Varas%20Cabanas%20Lago",
    url: "https://www.instagram.com/reel/DVPWP04j4aq/",
    poster: "thumbs/thumb_DVPWP04j4aq.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    tags: ["camping", "cabana", "lago", "ensenada", "asado", "picnic"],
    isTop: true
  },
  {
    id: 2,
    shortcode: "DUXC2OggLTC",
    titulo: "Mis 7 Cabañas Favoritas con Tinaja & Lago",
    lugar: "Especial 7 Cabañas Top",
    handle: "@datitosdelajose",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "Top 7 Recomendadas",
    descripcion: "Mis 7 cabañas favoritas en Puerto Varas y Ensenada con tinaja caliente de madera, piscina climatizada y/o acceso directo al lago Llanquihue comprobadas por mí.",
    detalles: "• Casa Pumahue: Tinaja caliente y vista a volcanes\n• Cantos del Chucao: Tinaja privada en bosque nativo\n• Bahía Celeste: Orilla de lago privada\n• Cabañas Rucamalén: Piscina climatizada y tinaja\n• Domos Anulén: Tinaja y terraza panorámica\n• Hospedaje Toqui: Tinaja y acceso al lago\n• Hotel Cabaña del Lago: Spa & tinajas",
    direccion: "Puerto Varas, Ensenada y Lago Llanquihue",
    whatsapp: "+56973984624",
    whatsappUrl: "https://wa.me/56973984624?text=Hola!%20Vi%20el%20especial%20de%20cabañas%20de%20Mamá%20Santi%20y%20quisiera%20más%20información.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?type=cabin",
    url: "https://www.instagram.com/p/DUXC2OggLTC/",
    poster: "thumbs/thumb_DUXC2OggLTC.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80",
    tags: ["cabanas", "tinajas", "piscina", "ranking", "lago"],
    isTop: true
  },
  {
    id: 3,
    shortcode: "DURRUl4j00E",
    titulo: "Hospedaje & Cabañas Toqui en Ensenada",
    lugar: "Cabañas Toqui",
    handle: "@datitosdelajose • @hospedajeycabanastoqui",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "Tinaja & Playa",
    descripcion: "Excelente experiencia de desconexión en Hospedaje y Cabañas Toqui. Cabañas cálidas y confortables con tinaja caliente a pasos del lago Llanquihue y vista abierta al Volcán Osorno.",
    detalles: " Km 42 Ensenada - Puerto Varas\n• WhatsApp: +56975247079",
    direccion: "Ruta 225 Km 42, Ensenada, Puerto Varas",
    whatsapp: "+56975247079",
    whatsappUrl: "https://wa.me/56975247079?text=Hola!%20Vi%20su%20cabaña%20en%20los%20reels%20de%20Mamá%20Santi%20(@datitosdelajose)%20y%20quiero%20consultar%20por%20arriendo.",
    airbnbUrl: "https://www.airbnb.cl/s/Ensenada--Puerto-Varas--Chile/homes?query=Cabanas%20Toqui%20Ensenada",
    url: "https://www.instagram.com/reel/DURRUl4j00E/",
    poster: "thumbs/thumb_DURRUl4j00E.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
    tags: ["cabanas", "tinajas", "ensenada", "descanso", "familia"],
    isTop: false
  },
  {
    id: 4,
    shortcode: "DRieRJpD8ga",
    titulo: "Escapada a Frutillar · Ciudad de la Música",
    lugar: "Circuito Frutillar Patrimonial",
    handle: "@datitosdelajose",
    categoria: "aventura",
    categoriaLabel: "Paseos & Panoramas",
    vistas: "Imperdible del Sur",
    descripcion: "🎻 Frutillar es conocida como 'La ciudad de la música'. Alternativas imperdibles para una escapada perfecta frente al lago: Casa Ayacara, Anoka Frutillar, Hotel Frutillar, Casa Winkler y Playa Maqui Lodge.",
    detalles: "• Casa Ayacara: Av. Philippi 1215 (+56974989154)\n• Anoka Frutillar: 21 de mayo 130 (+56961010914)\n• Casa Winkler: Av. Philippi 115 (+56652421388)\n• Playa Maqui Lodge: Km 23.2 (+56995678446)",
    direccion: "Av. Philippi, Costanera Frutillar Bajo",
    whatsapp: "+56974989154",
    whatsappUrl: "https://wa.me/56974989154?text=Hola!%20Vi%20la%20guía%20de%20Frutillar%20de%20Mamá%20Santi%20y%20me%20gustaría%20saber%20más.",
    airbnbUrl: "https://www.airbnb.cl/s/Frutillar--Chile/homes",
    url: "https://www.instagram.com/p/DRieRJpD8ga/",
    poster: "thumbs/thumb_DRieRJpD8ga.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    tags: ["frutillar", "patrimonio", "musica", "teatro", "kuchen"],
    isTop: false
  },
  {
    id: 5,
    shortcode: "DMgjOk3PULT",
    titulo: "Refugio Río Blanco · Cabaña de Ensueño & Cascada",
    lugar: "Refugio Río Blanco",
    handle: "@datitosdelajose • @refugio_rio.blanco",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "Tinaja Mágica",
    descripcion: "🎂 Un cumpleaños de ensueño en Refugio Río Blanco. Un lugar lleno de magia y naturaleza nativa a menos de 1 hora del centro de Puerto Varas. Cabaña full equipada para 5 personas con tinaja caliente bajo los árboles.",
    detalles: " Camino a Ensenada, sector Cascada Río Blanco.\n• Capacidad para 5 personas, estufa a leña y tinaja privada.",
    direccion: "Camino a Ensenada, Sector Río Blanco, Puerto Varas",
    whatsapp: "+56997164401",
    whatsappUrl: "https://wa.me/56997164401?text=Hola!%20Vi%20el%20video%20de%20Refugio%20Río%20Blanco%20en%20Mamá%20Santi%20y%20quiero%20cotizar%20estadía.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Refugio%20Rio%20Blanco%20Cabana",
    url: "https://www.instagram.com/reel/DMgjOk3PULT/",
    poster: "thumbs/thumb_DMgjOk3PULT.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
    tags: ["cabana", "tinaja", "bosque", "cascada", "rioblanco"],
    isTop: true
  },
  {
    id: 6,
    shortcode: "DMO2XZqgAv7",
    titulo: "Piscinas Climatizadas & Tinajas Todo el Año",
    lugar: "Guía de Piscinas & Tinajas",
    handle: "@datitosdelajose",
    categoria: "tinajas",
    categoriaLabel: "Tinajas & Spa",
    vistas: "Abierto a Todo Público",
    descripcion: "🏊‍♀️ Mis recomendados de piscinas climatizadas y tinajas calientes durante todo el año, ¡sin necesidad de ser huésped! Ideales para los días de lluvia y frío en Puerto Varas.",
    detalles: "▪︎ Cabañas Rucamalén (Km 36 camino a Ensenada): Piscina 4 hrs $15.000 adultos, tinaja 2 hrs $35.000.\n▪︎ Hotel Cabaña del Lago (Klenner 195): La piscina climatizada más grande de la región.\n▪︎ Aremko Spa (Km 4 Río Pescado): Tinajas en el bosque.",
    direccion: "Puerto Varas & Camino a Ensenada",
    whatsapp: "+56956482005",
    whatsappUrl: "https://wa.me/56956482005?text=Hola!%20Vi%20el%20dato%20de%20piscinas%20climatizadas%20de%20Mamá%20Santi%20y%20quiero%20reservar.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?amenities%5B%5D=7",
    url: "https://www.instagram.com/p/DMO2XZqgAv7/",
    poster: "thumbs/thumb_DMO2XZqgAv7.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80",
    tags: ["piscina", "tinajas", "spa", "lluvia", "relax"],
    isTop: true
  },
  {
    id: 7,
    shortcode: "DI2AjSZPe8b",
    titulo: "Domos & Cabañas Anulén · Vista al Volcán Osorno",
    lugar: "Domos & Cabañas Anulén",
    handle: "@datitosdelajose • @domosanulen",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "Tinaja & Parrilla Privada",
    descripcion: "🌅 ¡Relajo mágico en Domos y Cabañas Anulén! Lo pasamos realmente increíble. Cada domo y cabaña cuenta con su propia tinaja caliente de madera y parrilla en la terraza con una postal panorámica al volcán Osorno.",
    detalles: " Km 25.9 Sector Los Riscos, camino a Ensenada, Puerto Varas.\n� WhatsApp reservas: +56997164401",
    direccion: "Ruta 225 Km 25.9, Sector Los Riscos, Puerto Varas",
    whatsapp: "+56997164401",
    whatsappUrl: "https://wa.me/56997164401?text=Hola!%20Vi%20los%20Domos%20Anulén%20en%20los%20reels%20de%20Mamá%20Santi%20(@datitosdelajose)%20y%20quiero%20cotizar%20un%20domo.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Domos%20Anulen%20Los%20Riscos",
    url: "https://www.instagram.com/reel/DI2AjSZPe8b/",
    poster: "thumbs/thumb_DI2AjSZPe8b.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80",
    tags: ["domos", "cabanas", "tinaja", "volcanosorno", "losriscos"],
    isTop: true
  },
  {
    id: 8,
    shortcode: "DIxasMLAr4W",
    titulo: "Los Mejores Desayunos Buffet Abiertos al Público",
    lugar: "Circuito de Buffets Puerto Varas",
    handle: "@datitosdelajose",
    categoria: "desayunos",
    categoriaLabel: "Desayunos Buffet",
    vistas: "Guía Gastronómica",
    descripcion: "🥐 Los mejores desayunos buffet de la zona abiertos a todo público (no requieres estar hospedado): Doña Inés en Casino Dreams, Hotel Cabaña del Lago, Park Inn by Radisson, Hotel Gran Pacífico y Hotel Germania.",
    detalles: "• Doña Inés (Casino Dreams): Frente al lago\n• Hotel Cabaña del Lago: Repostería local de excelencia\n• Park Inn Radisson ($12.900): Vistas panorámicas\n• Hotel Germania ($12.000): Clásica pastelería alemana",
    direccion: "Puerto Varas y Puerto Montt",
    whatsapp: "+56999001122",
    whatsappUrl: "https://wa.me/56999001122?text=Hola!%20Vi%20la%20guía%20de%20desayunos%20buffet%20de%20Mamá%20Santi%20y%20quisiera%20consultar%20horarios.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes",
    url: "https://www.instagram.com/p/DIxasMLAr4W/",
    poster: "thumbs/thumb_DIxasMLAr4W.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=800&q=80",
    tags: ["buffet", "desayuno", "gastronomia", "pasteleria", "cafe"],
    isTop: true
  },
  {
    id: 9,
    shortcode: "DIg8vHpA9A0",
    titulo: "Cabañas Rucamalén · Piscina Climatizada & Lago",
    lugar: "Cabañas Rucamalén",
    handle: "@datitosdelajose • @cabanas__rucamalen",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "Piscina Climatizada & Sauna",
    descripcion: "🏊‍♀️ Fin de semana de relajo total en Cabañas Rucamalén: Cabañas a orilla del lago Llanquihue, piscina climatizada temperada, tinajas calientes, sauna de ciprés, kayaks y estacionamiento para Motorhome.",
    detalles: " Camino a Ensenada Km 36, Puerto Varas.\n� Reservas WhatsApp: +56956482005",
    direccion: "Ruta 225 Km 36, Camino a Ensenada, Puerto Varas",
    whatsapp: "+56956482005",
    whatsappUrl: "https://wa.me/56956482005?text=Hola!%20Vi%20el%20video%20de%20Cabañas%20Rucamalén%20en%20Mamá%20Santi%20(@datitosdelajose)%20y%20quiero%20cotizar%20cabaña/piscina.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Cabanas%20Rucamalen%20Ensenada",
    url: "https://www.instagram.com/reel/DIg8vHpA9A0/",
    poster: "thumbs/thumb_DIg8vHpA9A0.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80",
    tags: ["cabanas", "piscina", "tinajas", "sauna", "lago", "kayak"],
    isTop: true
  },
  {
    id: 10,
    shortcode: "DIF0YQjgzZ6",
    titulo: "Casa Pumahue · Vista a los Volcanes & Glamping",
    lugar: "Casa Pumahue",
    handle: "@datitosdelajose • @casa_pumahue",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "Tinaja & Desayuno Pumahue",
    descripcion: "Con una maravillosa vista panorámica a los volcanes y al lago Llanquihue, se encuentra Casa Pumahue cerca del Parque Nacional Vicente Pérez Rosales. Cabañas, domos, glamping y tinajas con desayuno casero.",
    detalles: "� WhatsApp directo: +56973984624\n• Sector Ensenada, a minutos de Saltos del Petrohué.",
    direccion: "Camino a Ensenada s/n, cercano a Parque Vicente Pérez Rosales",
    whatsapp: "+56973984624",
    whatsappUrl: "https://wa.me/56973984624?text=Hola!%20Vi%20Casa%20Pumahue%20en%20el%20perfil%20de%20Mamá%20Santi%20(@datitosdelajose)%20y%20quiero%20reservar.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Casa%20Pumahue%20Ensenada",
    url: "https://www.instagram.com/reel/DIF0YQjgzZ6/",
    poster: "thumbs/thumb_DIF0YQjgzZ6.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80",
    tags: ["glamping", "domos", "tinajas", "volcanes", "petrohue"],
    isTop: false
  },
  {
    id: 11,
    shortcode: "DHrIE4RPTD0",
    titulo: "Cabañas Bahía Celeste · A 25 min de Puerto Varas",
    lugar: "Cabañas Bahía Celeste",
    handle: "@datitosdelajose • @bahia_celeste",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "Orilla Directa de Lago",
    descripcion: "Relajo total en Cabañas Bahía Celeste, a solo 25 minutos del centro de Puerto Varas. Cabañas familiares y de pareja para 2, 4, 5 y 6 personas situadas exactamente al borde del lago con bajada directa.",
    detalles: " Km 21 camino a Ensenada, Puerto Varas\n• WhatsApp: +56993287634",
    direccion: "Ruta 225 Km 21, Camino a Ensenada, Puerto Varas",
    whatsapp: "+56993287634",
    whatsappUrl: "https://wa.me/56993287634?text=Hola!%20Vi%20Cabañas%20Bahía%20Celeste%20en%20los%20reels%20de%20Mamá%20Santi%20(@datitosdelajose)%20y%20quisiera%20consultar%20por%20arriendo.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Bahia%20Celeste%20Cabanas%20Puerto%20Varas",
    url: "https://www.instagram.com/reel/DHrIE4RPTD0/",
    poster: "thumbs/thumb_DHrIE4RPTD0.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
    tags: ["cabanas", "playa", "lago", "familia", "volcan"],
    isTop: false
  },
  {
    id: 12,
    shortcode: "DHZhDAzPzWl",
    titulo: "Park Inn by Radisson · Desayuno Buffet Panorámico",
    lugar: "Park Inn by Radisson Puerto Varas",
    handle: "@datitosdelajose • @parkinnbyradissonpv",
    categoria: "desayunos",
    categoriaLabel: "Desayunos Buffet",
    vistas: "$12.900 Todo Público",
    descripcion: "🚗 Tradicional arquitectura alemana y vistas panorámicas de postal en Park Inn by Radisson con un exquisito buffet abierto a público de lunes a domingo de 7:00 a 10:30 de la mañana.",
    detalles: "� Valor: $12.900 por persona\n• La Paz 471, Puerto Varas.",
    direccion: "La Paz 471, Puerto Varas",
    whatsapp: "+56652231100",
    whatsappUrl: "https://wa.me/56652231100?text=Hola!%20Vi%20el%20desayuno%20buffet%20en%20los%20reels%20de%20Mamá%20Santi%20y%20quisiera%20consultar.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes",
    url: "https://www.instagram.com/reel/DHZhDAzPzWl/",
    poster: "thumbs/thumb_DHZhDAzPzWl.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80",
    tags: ["radisson", "buffet", "hotel", "desayuno", "panoramico"],
    isTop: false
  },
  {
    id: 13,
    shortcode: "DHT3z_KvxTF",
    titulo: "Hotel Cabaña del Lago · Buffet, Almuerzo & Piscina",
    lugar: "Hotel Cabaña del Lago",
    handle: "@datitosdelajose • @hotel_cdl",
    categoria: "tinajas",
    categoriaLabel: "Tinajas & Spa",
    vistas: "Pack Almuerzo + Piscina",
    descripcion: "🧳 El clásico por excelencia en Puerto Varas: Desayuno buffet abierto a todo público con pastelería de autor y productos locales. Pack almuerzo más piscina temperada ($36.900 adultos) y karaoke los fines de semana.",
    detalles: " Klenner 195, Puerto Varas\n�‍♂️ Piscina temperada + gastronomía de autor frente a los volcanes.",
    direccion: "Klenner 195, Puerto Varas",
    whatsapp: "+56999001122",
    whatsappUrl: "https://wa.me/56999001122?text=Hola!%20Vi%20el%20pack%20de%20piscina%20y%20buffet%20de%20Cabaña%20del%20Lago%20en%20Mamá%20Santi.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Hotel%20Cabana%20del%20Lago",
    url: "https://www.instagram.com/reel/DHT3z_KvxTF/",
    poster: "thumbs/thumb_DHT3z_KvxTF.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
    tags: ["hotel", "piscina", "buffet", "karaoke", "spa"],
    isTop: true
  },
  {
    id: 14,
    shortcode: "DHJdBAcgxXF",
    titulo: "El Gran Recorrido de la Jose por el Sur de Chile",
    lugar: "Ruta 3 Semanas por Los Lagos",
    handle: "@datitosdelajose",
    categoria: "aventura",
    categoriaLabel: "Paseos & Panoramas",
    vistas: "Ruta Completa",
    descripcion: "🧳 Recorrido de casi 3 semanas conociendo los rincones más mágicos del sur: Cabaña del Lago, Park Inn Radisson, Casa Pumahue, Bahía Celeste, La Jardinera, Cabañas Rucamalén, Domos Anulén, Alma Vista Spa y Termas del Sol.",
    detalles: "� Itinerario curado que une Puerto Varas, Ensenada, Frutillar y las Termas de Cochamó.",
    direccion: "Circuito Lago Llanquihue & Región de Los Lagos",
    whatsapp: "+56999967272",
    whatsappUrl: "https://wa.me/56999967272?text=Hola%20Jose!%20Quiero%20planificar%20mi%20viaje%20con%20tu%20recorrido%20por%20el%20sur.",
    airbnbUrl: "https://www.airbnb.cl/s/Region-de-los-Lagos--Chile/homes",
    url: "https://www.instagram.com/reel/DHJdBAcgxXF/",
    poster: "thumbs/thumb_DHJdBAcgxXF.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    tags: ["itinerario", "recorrido", "surdechile", "termas", "rutacompleta"],
    isTop: true
  },
  {
    id: 15,
    shortcode: "DBmZzFGyEn1",
    titulo: "Restaurant Los Navegantes · Hotel Gran Pacífico",
    lugar: "Restaurant Los Navegantes",
    handle: "@datitosdelajose • @granpacificohotel",
    categoria: "desayunos",
    categoriaLabel: "�️ Gastronomía Marina",
    vistas: "Sugerencias del Chef",
    descripcion: "👨‍🍳 ¡Un manjarsssh! Tienen que probar 'Las sugerencias del chef' en Restaurant Los Navegantes: salmón crispy sobre risotto de mote y mariscos del seno de Reloncaví con carta premium.",
    detalles: " Urmeneta 719, Puerto Montt\n� Reservas: +56985261885\n� Platos entre $9.990 y $14.500",
    direccion: "Urmeneta 719, Puerto Montt",
    whatsapp: "+56985261885",
    whatsappUrl: "https://wa.me/56985261885?text=Hola!%20Vi%20la%20recomendación%20del%20Restaurante%20Los%20Navegantes%20en%20Mamá%20Santi%20y%20quiero%20reservar.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Montt--Chile/homes",
    url: "https://www.instagram.com/reel/DBmZzFGyEn1/",
    poster: "thumbs/thumb_DBmZzFGyEn1.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    tags: ["gourmet", "salmon", "chef", "mariscos", "puertomontt"],
    isTop: false
  },
  {
    id: 16,
    shortcode: "C-wDBXtu6Us",
    titulo: "Cabañas Cantos del Chucao · Calificación 10/10",
    lugar: "Cabañas Cantos del Chucao",
    handle: "@datitosdelajose • @cantosdelchucao",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "10/10 Recomendado",
    descripcion: "A solo 20 minutos y 19 km de Puerto Varas, en Colonia Tres Puentes, están las increíbles cabañas Cantos del Chucao. Cabaña íntima de madera para 2 con tinaja de ciprés, parrilla y combustión lenta. ¡Mi nota es 10/10!",
    detalles: "• Cabaña de 2 personas con tinaja privada y wifi\n• Cabaña para 9 personas\n� WhatsApp: +56983244111",
    direccion: "Sector Colonia Tres Puentes, Puerto Varas",
    whatsapp: "+56983244111",
    whatsappUrl: "https://wa.me/56983244111?text=Hola!%20Vi%20Cabañas%20Cantos%20del%20Chucao%20con%20nota%2010/10%20en%20Mamá%20Santi%20y%20quiero%20arrendar.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Cantos%20del%20Chucao%20Tres%20Puentes",
    url: "https://www.instagram.com/reel/C-wDBXtu6Us/",
    poster: "thumbs/thumb_C-wDBXtu6Us.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
    tags: ["cabana", "bosque", "tinaja", "romantico", "chucao"],
    isTop: true
  },
  {
    id: 17,
    shortcode: "C8viWkou1y6",
    titulo: "Desayuno Buffet Hotel Germania · Pastelería Alemana",
    lugar: "Hotel Germania Puerto Varas",
    handle: "@datitosdelajose • @hotelgermania_puertovaras",
    categoria: "desayunos",
    categoriaLabel: "Desayunos Buffet",
    vistas: "Buffet $12.000",
    descripcion: "Partiendo el día con energía: El buffet de Hotel Germania es realmente rico. De 7:00 a 11:00 hrs con recetas generacionales alemanas, küchens caseros y wifi excelente si requieres trabajar.",
    detalles: "� Valor: $12.000 por persona\n• San Ignacio 1286, Puerto Varas",
    direccion: "San Ignacio 1286, Puerto Varas",
    whatsapp: "+56652232444",
    whatsappUrl: "https://wa.me/56652232444?text=Hola!%20Vi%20el%20desayuno%20buffet%20de%20Hotel%20Germania%20en%20Mamá%20Santi%20(@datitosdelajose).",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes",
    url: "https://www.instagram.com/reel/C8viWkou1y6/",
    poster: "thumbs/thumb_C8viWkou1y6.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80",
    tags: ["buffet", "kuchen", "germania", "cafe", "trabajo"],
    isTop: false
  },
  {
    id: 18,
    shortcode: "C8dC4gFOpV2",
    titulo: "Restaurant Hotel Ibis · Salmón con Salsa de Camarón",
    lugar: "Restaurant Hotel Ibis",
    handle: "@datitosdelajose • @hotelibispuertomontt",
    categoria: "desayunos",
    categoriaLabel: "�️ Gastronomía Marina",
    vistas: "Música en Vivo",
    descripcion: "🍽️ Fuimos a conocer el restaurante de Hotel Ibis y nos encontramos con entretenida música en vivo. Les recomiendo el salmón sellado con salsa cremosa de camarón acompañado de un exquisito risotto de mote.",
    detalles: " Diego Portales 1001, Costanera Puerto Montt",
    direccion: "Diego Portales 1001, Puerto Montt",
    whatsapp: "+56652431000",
    whatsappUrl: "https://wa.me/56652431000?text=Hola!%20Vi%20el%20restaurante%20de%20Hotel%20Ibis%20en%20los%20reels%20de%20Mamá%20Santi.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Montt--Chile/homes",
    url: "https://www.instagram.com/reel/C8dC4gFOpV2/",
    poster: "thumbs/thumb_C8dC4gFOpV2.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    tags: ["salmon", "risotto", "musica", "restaurante"],
    isTop: false
  },
  {
    id: 19,
    shortcode: "C67cjTcujYF",
    titulo: "Cabañas Bosque Sur · Naturaleza Nativa en Puerto Varas",
    lugar: "Cabañas Bosque Sur",
    handle: "@datitosdelajose • @cabanas_bosquesurpv",
    categoria: "cabanas",
    categoriaLabel: "Cabañas & Airbnb",
    vistas: "Bosque Nativo",
    descripcion: "Cabañas matrimoniales y familiares inmersas en el verde del bosque nativo. El refugio perfecto para descansar en pareja o familia con el silencio de la naturaleza sureña.",
    detalles: " Puerto Varas, Región de Los Lagos\n• Cabañas full equipadas con estufa y terraza.",
    direccion: "Sector Rural Camino a Alerce, Puerto Varas",
    whatsapp: "+56999967272",
    whatsappUrl: "https://wa.me/56999967272?text=Hola!%20Vi%20Cabañas%20Bosque%20Sur%20en%20Mamá%20Santi%20(@datitosdelajose)%20y%20quiero%20consultar.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Cabanas%20Bosque%20Sur",
    url: "https://www.instagram.com/reel/C67cjTcujYF/",
    poster: "thumbs/thumb_C67cjTcujYF.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
    tags: ["cabana", "bosque", "naturaleza", "escapada"],
    isTop: false
  },
  {
    id: 20,
    shortcode: "C5xFK0sOYLn",
    titulo: "Show & Comedia en Casino Dreams Puerto Varas",
    lugar: "Casino Dreams Puerto Varas",
    handle: "@datitosdelajose • @dreamsptovaras",
    categoria: "aventura",
    categoriaLabel: "Shows & Vida Nocturna",
    vistas: "Costanera Puerto Varas",
    descripcion: "🎤 Noches de risa y entretenimiento en el Casino Dreams frente al lago. Cartelera de grandes comediantes, música en vivo y una vista insuperable de la bahía iluminada.",
    detalles: " Av. Vicente Pérez Rosales 689, Puerto Varas.",
    direccion: "Av. Vicente Pérez Rosales 689, Puerto Varas",
    whatsapp: "+56652492000",
    whatsappUrl: "https://wa.me/56652492000?text=Hola!%20Quisiera%20consultar%20por%20la%20cartelera%20de%20shows%20de%20Casino%20Dreams.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes",
    url: "https://www.instagram.com/reel/C5xFK0sOYLn/",
    poster: "thumbs/thumb_C5xFK0sOYLn.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
    tags: ["casino", "comedia", "shows", "noche", "dreams"],
    isTop: false
  },
  {
    id: 21,
    shortcode: "C3oOZL5OXWS",
    titulo: "Camping Don Chucao · Carpas Colgantes en Caleta Rollizo",
    lugar: "Camping Don Chucao",
    handle: "@datitosdelajose • @campingdonchucao",
    categoria: "glamping",
    categoriaLabel: "Glamping & Bosque",
    vistas: "Dormir en el Aire",
    descripcion: "¡¡Carpas Colgantes!! Ultra entretenida experiencia dormir suspendido en el aire en medio del bosque nativo en Camping Don Chucao. Por la mañana un rico desayuno campestre elaborado con amor por su dueña Mireya.",
    detalles: " A 86 km de Puerto Varas y a 700 m de Caleta Rollizo\n� WhatsApp: +56979292090\n� Desayuno campestre artesanal incluido.",
    direccion: "Caleta Rollizo s/n, a 86 km de Puerto Varas",
    whatsapp: "+56979292090",
    whatsappUrl: "https://wa.me/56979292090?text=Hola%20Mireya!%20Vi%20las%20carpas%20colgantes%20en%20el%20reel%20de%20Mamá%20Santi%20(@datitosdelajose)%20y%20quiero%20reservar.",
    airbnbUrl: "https://www.airbnb.cl/s/Caleta-Rollizo--Chile/homes?query=Camping%20Don%20Chucao%20Rollizo",
    url: "https://www.instagram.com/reel/C3oOZL5OXWS/",
    poster: "thumbs/thumb_C3oOZL5OXWS.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=800&q=80",
    tags: ["glamping", "carpascolgantes", "bosque", "rollizo", "desayunocampestre"],
    isTop: true
  },
  {
    id: 22,
    shortcode: "C2D-y1_OH3Z",
    titulo: "Origen Patagonia Verde · Yurta & Baños de Bosque",
    lugar: "Origen Patagonia Verde",
    handle: "@datitosdelajose • @origenpatagoniaverde",
    categoria: "glamping",
    categoriaLabel: "Glamping & Bosque",
    vistas: "Yurta & Shinrin Yoku",
    descripcion: "Muy buen dato para una escapada diferente: Duerme en una Yurta en el bosque con tinaja privada y todas las comodidades. Además puedes ir por el día a senderismo contemplativo guiado, Shinrin Yoku (Baños del bosque) y yoga.",
    detalles: " Sector Totoral, a 15 minutos de Puerto Varas\n� Reserva en: +56942492462",
    direccion: "Sector Totoral, a 15 min de Puerto Varas",
    whatsapp: "+56942492462",
    whatsappUrl: "https://wa.me/56942492462?text=Hola!%20Vi%20la%20yurta%20y%20baños%20de%20bosque%20en%20los%20reels%20de%20Mamá%20Santi%20(@datitosdelajose)%20y%20quiero%20reservar.",
    airbnbUrl: "https://www.airbnb.cl/s/Puerto-Varas--Chile/homes?query=Yurta%20Origen%20Patagonia%20Verde%20Totoral",
    url: "https://www.instagram.com/reel/C2D-y1_OH3Z/",
    poster: "thumbs/thumb_C2D-y1_OH3Z.jpg",
    fallbackPoster: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80",
    tags: ["yurta", "glamping", "shinrinyoku", "tinaja", "bosque", "yoga"],
    isTop: true
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { REELS_DATA };
}
